
(defun th-c++-mode-handler()
  "Tooltip handler for C++"
  (let* ((name (current-word))
	 (buf (concat name ".3.html"))
	 (url (concat "http://www.rt.com/man/" name ".3.html"))
	 (cur (current-buffer)))
    (if (get-buffer buf)
	(kill-buffer buf))
    (with-current-buffer (browse-url-emacs url)
      (let ((buffer-read-only nil))
	(beginning-of-buffer)
	(search-forward "<pre>")
	(next-line)
	(beginning-of-line)
	(delete-region (point-min) (point))
	(set-buffer-modified-p nil)
	(search-forward "</pre>")
	(beginning-of-line)
	(delete-region (point) (point-max))
	(set-buffer-modified-p nil)
	(beginning-of-buffer)
	(while (search-forward-regexp "<[^>]*>"  nil t)
	  (put-text-property (match-beginning 0)
			     (match-end 0)
			     'invisible t
			     ))
	(beginning-of-buffer)
	(while (search-forward-regexp "&lt;"  nil t)
	  (put-text-property (match-beginning 0)
			     (match-end 0)
			     'display 
			     "<"
			     ))
	(beginning-of-buffer)
	(while (search-forward-regexp "&gt;"  nil t)
	  (put-text-property (match-beginning 0)
			     (match-end 0)
			     'display 
			     ">"
			     ))
	(beginning-of-buffer)
	(while (search-forward ""  nil t)
	  (put-text-property (match-beginning 0)
			     (match-end 0)
			     'invisible t 
			     ))
	(beginning-of-buffer)
	(set-buffer-modified-p nil))
      )
    "")
  )