###############################################################################
###   This file has been generated by a script -- don't modify it by hand   ###
###############################################################################

###############################################################################
# This generated file is meant to help the creation of awk script which deals
# with spu asm instruction.
# By using this files, several variables will be set with information about
# those instructions.
#
# - spu_cmd_count: scalar type
#     reference the total number of spu instructions
# - spu_cmd_list: array type 1D
#     access: spu_cmd_list[N]
#     contains the name of the Nth instruction of the spu stored in this array
#
# - spu_cmd_latency: array type 1D
#     access: spu_cmd_latency[cmd_name]
#     contains the latency of the instruction named: cmd_name
# - spu_cmd_pipe: array type 1D
#     access: spu_cmd_pipe[cmd_name]
#     contains the pipe name ("even" or "odd") of the instruction: cmd_name
# - spu_cmd_argc: array type 1D <deprecated>
#     access: spu_cmd_argc[cmd_name]
#     contains the number of argument for the instruction: cmd_name
#     This variable is deprecated and is matching the minimum value.
# - spu_cmd_minc: array type 1D
#     contains the minimum number of argument for the instruction: cmd_name
# - spu_cmd_maxc: array type 1D
#     contains the maximum number of argument for the instruction: cmd_name
# - spu_cmd_argv: array type 2D
#     access: spu_cmd_argv[cmd_name, arg_ndx]
#     contains the type of the "arg_ndx"th argument for the instr cmd_name
#
#------------------------------------------------------------------------------
# Description of each argument type:
#   "ro": read only register
#   "wo": write only register
#   "rw": read/write register
#   "ir": immediate value added to a read only register -- form: imm(reg)
#   "im": immediate value
#   "sr": special purpose register
#   "ch": channel
#   "br": branch label
#   "lb": offset label
# Some parameter might be optional, in that case a  "!" is inserted as first
# character. e.g: "ro"
#
# Note: the indices range are 0 to N-1
###############################################################################

BEGIN {
	# Initialization:
	spu_cmd_count = 0;

	# Command: NOP
	spu_cmd_list[spu_cmd_count++] = "NOP"
	spu_cmd_latency["NOP"] = 1
	spu_cmd_pipe["NOP"] = "even"
	spu_cmd_argv["NOP", 0] = "!rw"
	spu_cmd_argc["NOP"] = 0
	spu_cmd_minc["NOP"] = 0
	spu_cmd_maxc["NOP"] = 1

	# Command: HEQ
	spu_cmd_list[spu_cmd_count++] = "HEQ"
	spu_cmd_latency["HEQ"] = 2
	spu_cmd_pipe["HEQ"] = "even"
	spu_cmd_argv["HEQ", 0] = "ro"
	spu_cmd_argv["HEQ", 1] = "ro"
	spu_cmd_argc["HEQ"] = 2
	spu_cmd_minc["HEQ"] = 2
	spu_cmd_maxc["HEQ"] = 2

	# Command: HEQI
	spu_cmd_list[spu_cmd_count++] = "HEQI"
	spu_cmd_latency["HEQI"] = 2
	spu_cmd_pipe["HEQI"] = "even"
	spu_cmd_argv["HEQI", 0] = "!wo"
	spu_cmd_argv["HEQI", 1] = "ro"
	spu_cmd_argv["HEQI", 2] = "im"
	spu_cmd_argc["HEQI"] = 2
	spu_cmd_minc["HEQI"] = 2
	spu_cmd_maxc["HEQI"] = 3

	# Command: HGT
	spu_cmd_list[spu_cmd_count++] = "HGT"
	spu_cmd_latency["HGT"] = 2
	spu_cmd_pipe["HGT"] = "even"
	spu_cmd_argv["HGT", 0] = "!wo"
	spu_cmd_argv["HGT", 1] = "ro"
	spu_cmd_argv["HGT", 2] = "ro"
	spu_cmd_argc["HGT"] = 2
	spu_cmd_minc["HGT"] = 2
	spu_cmd_maxc["HGT"] = 3

	# Command: HGTI
	spu_cmd_list[spu_cmd_count++] = "HGTI"
	spu_cmd_latency["HGTI"] = 2
	spu_cmd_pipe["HGTI"] = "even"
	spu_cmd_argv["HGTI", 0] = "!wo"
	spu_cmd_argv["HGTI", 1] = "ro"
	spu_cmd_argv["HGTI", 2] = "im"
	spu_cmd_argc["HGTI"] = 2
	spu_cmd_minc["HGTI"] = 2
	spu_cmd_maxc["HGTI"] = 3

	# Command: HLGT
	spu_cmd_list[spu_cmd_count++] = "HLGT"
	spu_cmd_latency["HLGT"] = 2
	spu_cmd_pipe["HLGT"] = "even"
	spu_cmd_argv["HLGT", 0] = "!wo"
	spu_cmd_argv["HLGT", 1] = "ro"
	spu_cmd_argv["HLGT", 2] = "ro"
	spu_cmd_argc["HLGT"] = 2
	spu_cmd_minc["HLGT"] = 2
	spu_cmd_maxc["HLGT"] = 3

	# Command: HLGTI
	spu_cmd_list[spu_cmd_count++] = "HLGTI"
	spu_cmd_latency["HLGTI"] = 2
	spu_cmd_pipe["HLGTI"] = "even"
	spu_cmd_argv["HLGTI", 0] = "!wo"
	spu_cmd_argv["HLGTI", 1] = "ro"
	spu_cmd_argv["HLGTI", 2] = "im"
	spu_cmd_argc["HLGTI"] = 2
	spu_cmd_minc["HLGTI"] = 2
	spu_cmd_maxc["HLGTI"] = 3

	# Command: FA
	spu_cmd_list[spu_cmd_count++] = "FA"
	spu_cmd_latency["FA"] = 6
	spu_cmd_pipe["FA"] = "even"
	spu_cmd_argv["FA", 0] = "wo"
	spu_cmd_argv["FA", 1] = "ro"
	spu_cmd_argv["FA", 2] = "ro"
	spu_cmd_argc["FA"] = 3
	spu_cmd_minc["FA"] = 3
	spu_cmd_maxc["FA"] = 3

	# Command: FS
	spu_cmd_list[spu_cmd_count++] = "FS"
	spu_cmd_latency["FS"] = 6
	spu_cmd_pipe["FS"] = "even"
	spu_cmd_argv["FS", 0] = "wo"
	spu_cmd_argv["FS", 1] = "ro"
	spu_cmd_argv["FS", 2] = "ro"
	spu_cmd_argc["FS"] = 3
	spu_cmd_minc["FS"] = 3
	spu_cmd_maxc["FS"] = 3

	# Command: FM
	spu_cmd_list[spu_cmd_count++] = "FM"
	spu_cmd_latency["FM"] = 6
	spu_cmd_pipe["FM"] = "even"
	spu_cmd_argv["FM", 0] = "wo"
	spu_cmd_argv["FM", 1] = "ro"
	spu_cmd_argv["FM", 2] = "ro"
	spu_cmd_argc["FM"] = 3
	spu_cmd_minc["FM"] = 3
	spu_cmd_maxc["FM"] = 3

	# Command: FMA
	spu_cmd_list[spu_cmd_count++] = "FMA"
	spu_cmd_latency["FMA"] = 6
	spu_cmd_pipe["FMA"] = "even"
	spu_cmd_argv["FMA", 0] = "wo"
	spu_cmd_argv["FMA", 1] = "ro"
	spu_cmd_argv["FMA", 2] = "ro"
	spu_cmd_argv["FMA", 3] = "ro"
	spu_cmd_argc["FMA"] = 4
	spu_cmd_minc["FMA"] = 4
	spu_cmd_maxc["FMA"] = 4

	# Command: FMS
	spu_cmd_list[spu_cmd_count++] = "FMS"
	spu_cmd_latency["FMS"] = 6
	spu_cmd_pipe["FMS"] = "even"
	spu_cmd_argv["FMS", 0] = "wo"
	spu_cmd_argv["FMS", 1] = "ro"
	spu_cmd_argv["FMS", 2] = "ro"
	spu_cmd_argv["FMS", 3] = "ro"
	spu_cmd_argc["FMS"] = 4
	spu_cmd_minc["FMS"] = 4
	spu_cmd_maxc["FMS"] = 4

	# Command: FNMS
	spu_cmd_list[spu_cmd_count++] = "FNMS"
	spu_cmd_latency["FNMS"] = 6
	spu_cmd_pipe["FNMS"] = "even"
	spu_cmd_argv["FNMS", 0] = "wo"
	spu_cmd_argv["FNMS", 1] = "ro"
	spu_cmd_argv["FNMS", 2] = "ro"
	spu_cmd_argv["FNMS", 3] = "ro"
	spu_cmd_argc["FNMS"] = 4
	spu_cmd_minc["FNMS"] = 4
	spu_cmd_maxc["FNMS"] = 4

	# Command: DFA
	spu_cmd_list[spu_cmd_count++] = "DFA"
	spu_cmd_latency["DFA"] = 13
	spu_cmd_pipe["DFA"] = "even"
	spu_cmd_argv["DFA", 0] = "wo"
	spu_cmd_argv["DFA", 1] = "ro"
	spu_cmd_argv["DFA", 2] = "ro"
	spu_cmd_argc["DFA"] = 3
	spu_cmd_minc["DFA"] = 3
	spu_cmd_maxc["DFA"] = 3

	# Command: DFS
	spu_cmd_list[spu_cmd_count++] = "DFS"
	spu_cmd_latency["DFS"] = 13
	spu_cmd_pipe["DFS"] = "even"
	spu_cmd_argv["DFS", 0] = "wo"
	spu_cmd_argv["DFS", 1] = "ro"
	spu_cmd_argv["DFS", 2] = "ro"
	spu_cmd_argc["DFS"] = 3
	spu_cmd_minc["DFS"] = 3
	spu_cmd_maxc["DFS"] = 3

	# Command: DFM
	spu_cmd_list[spu_cmd_count++] = "DFM"
	spu_cmd_latency["DFM"] = 13
	spu_cmd_pipe["DFM"] = "even"
	spu_cmd_argv["DFM", 0] = "wo"
	spu_cmd_argv["DFM", 1] = "ro"
	spu_cmd_argv["DFM", 2] = "ro"
	spu_cmd_argc["DFM"] = 3
	spu_cmd_minc["DFM"] = 3
	spu_cmd_maxc["DFM"] = 3

	# Command: DFMA
	spu_cmd_list[spu_cmd_count++] = "DFMA"
	spu_cmd_latency["DFMA"] = 13
	spu_cmd_pipe["DFMA"] = "even"
	spu_cmd_argv["DFMA", 0] = "wo"
	spu_cmd_argv["DFMA", 1] = "ro"
	spu_cmd_argv["DFMA", 2] = "ro"
	spu_cmd_argc["DFMA"] = 3
	spu_cmd_minc["DFMA"] = 3
	spu_cmd_maxc["DFMA"] = 3

	# Command: DFMS
	spu_cmd_list[spu_cmd_count++] = "DFMS"
	spu_cmd_latency["DFMS"] = 13
	spu_cmd_pipe["DFMS"] = "even"
	spu_cmd_argv["DFMS", 0] = "wo"
	spu_cmd_argv["DFMS", 1] = "ro"
	spu_cmd_argv["DFMS", 2] = "ro"
	spu_cmd_argc["DFMS"] = 3
	spu_cmd_minc["DFMS"] = 3
	spu_cmd_maxc["DFMS"] = 3

	# Command: DFNMA
	spu_cmd_list[spu_cmd_count++] = "DFNMA"
	spu_cmd_latency["DFNMA"] = 13
	spu_cmd_pipe["DFNMA"] = "even"
	spu_cmd_argv["DFNMA", 0] = "wo"
	spu_cmd_argv["DFNMA", 1] = "ro"
	spu_cmd_argv["DFNMA", 2] = "ro"
	spu_cmd_argc["DFNMA"] = 3
	spu_cmd_minc["DFNMA"] = 3
	spu_cmd_maxc["DFNMA"] = 3

	# Command: DFNMS
	spu_cmd_list[spu_cmd_count++] = "DFNMS"
	spu_cmd_latency["DFNMS"] = 13
	spu_cmd_pipe["DFNMS"] = "even"
	spu_cmd_argv["DFNMS", 0] = "wo"
	spu_cmd_argv["DFNMS", 1] = "ro"
	spu_cmd_argv["DFNMS", 2] = "ro"
	spu_cmd_argc["DFNMS"] = 3
	spu_cmd_minc["DFNMS"] = 3
	spu_cmd_maxc["DFNMS"] = 3

	# Command: FESD
	spu_cmd_list[spu_cmd_count++] = "FESD"
	spu_cmd_latency["FESD"] = 13
	spu_cmd_pipe["FESD"] = "even"
	spu_cmd_argv["FESD", 0] = "wo"
	spu_cmd_argv["FESD", 1] = "ro"
	spu_cmd_argc["FESD"] = 2
	spu_cmd_minc["FESD"] = 2
	spu_cmd_maxc["FESD"] = 2

	# Command: FRDS
	spu_cmd_list[spu_cmd_count++] = "FRDS"
	spu_cmd_latency["FRDS"] = 13
	spu_cmd_pipe["FRDS"] = "even"
	spu_cmd_argv["FRDS", 0] = "wo"
	spu_cmd_argv["FRDS", 1] = "ro"
	spu_cmd_argc["FRDS"] = 2
	spu_cmd_minc["FRDS"] = 2
	spu_cmd_maxc["FRDS"] = 2

	# Command: CNTB
	spu_cmd_list[spu_cmd_count++] = "CNTB"
	spu_cmd_latency["CNTB"] = 4
	spu_cmd_pipe["CNTB"] = "even"
	spu_cmd_argv["CNTB", 0] = "wo"
	spu_cmd_argv["CNTB", 1] = "ro"
	spu_cmd_argc["CNTB"] = 2
	spu_cmd_minc["CNTB"] = 2
	spu_cmd_maxc["CNTB"] = 2

	# Command: AVGB
	spu_cmd_list[spu_cmd_count++] = "AVGB"
	spu_cmd_latency["AVGB"] = 4
	spu_cmd_pipe["AVGB"] = "even"
	spu_cmd_argv["AVGB", 0] = "wo"
	spu_cmd_argv["AVGB", 1] = "ro"
	spu_cmd_argv["AVGB", 2] = "ro"
	spu_cmd_argc["AVGB"] = 3
	spu_cmd_minc["AVGB"] = 3
	spu_cmd_maxc["AVGB"] = 3

	# Command: ABSDB
	spu_cmd_list[spu_cmd_count++] = "ABSDB"
	spu_cmd_latency["ABSDB"] = 4
	spu_cmd_pipe["ABSDB"] = "even"
	spu_cmd_argv["ABSDB", 0] = "wo"
	spu_cmd_argv["ABSDB", 1] = "ro"
	spu_cmd_argv["ABSDB", 2] = "ro"
	spu_cmd_argc["ABSDB"] = 3
	spu_cmd_minc["ABSDB"] = 3
	spu_cmd_maxc["ABSDB"] = 3

	# Command: SUMB
	spu_cmd_list[spu_cmd_count++] = "SUMB"
	spu_cmd_latency["SUMB"] = 4
	spu_cmd_pipe["SUMB"] = "even"
	spu_cmd_argv["SUMB", 0] = "wo"
	spu_cmd_argv["SUMB", 1] = "ro"
	spu_cmd_argv["SUMB", 2] = "ro"
	spu_cmd_argc["SUMB"] = 3
	spu_cmd_minc["SUMB"] = 3
	spu_cmd_maxc["SUMB"] = 3

	# Command: SHLH
	spu_cmd_list[spu_cmd_count++] = "SHLH"
	spu_cmd_latency["SHLH"] = 4
	spu_cmd_pipe["SHLH"] = "even"
	spu_cmd_argv["SHLH", 0] = "wo"
	spu_cmd_argv["SHLH", 1] = "ro"
	spu_cmd_argv["SHLH", 2] = "ro"
	spu_cmd_argc["SHLH"] = 3
	spu_cmd_minc["SHLH"] = 3
	spu_cmd_maxc["SHLH"] = 3

	# Command: SHLHI
	spu_cmd_list[spu_cmd_count++] = "SHLHI"
	spu_cmd_latency["SHLHI"] = 4
	spu_cmd_pipe["SHLHI"] = "even"
	spu_cmd_argv["SHLHI", 0] = "wo"
	spu_cmd_argv["SHLHI", 1] = "ro"
	spu_cmd_argv["SHLHI", 2] = "im"
	spu_cmd_argc["SHLHI"] = 3
	spu_cmd_minc["SHLHI"] = 3
	spu_cmd_maxc["SHLHI"] = 3

	# Command: SHL
	spu_cmd_list[spu_cmd_count++] = "SHL"
	spu_cmd_latency["SHL"] = 4
	spu_cmd_pipe["SHL"] = "even"
	spu_cmd_argv["SHL", 0] = "wo"
	spu_cmd_argv["SHL", 1] = "ro"
	spu_cmd_argv["SHL", 2] = "ro"
	spu_cmd_argc["SHL"] = 3
	spu_cmd_minc["SHL"] = 3
	spu_cmd_maxc["SHL"] = 3

	# Command: SHLI
	spu_cmd_list[spu_cmd_count++] = "SHLI"
	spu_cmd_latency["SHLI"] = 4
	spu_cmd_pipe["SHLI"] = "even"
	spu_cmd_argv["SHLI", 0] = "wo"
	spu_cmd_argv["SHLI", 1] = "ro"
	spu_cmd_argv["SHLI", 2] = "im"
	spu_cmd_argc["SHLI"] = 3
	spu_cmd_minc["SHLI"] = 3
	spu_cmd_maxc["SHLI"] = 3

	# Command: ROTH
	spu_cmd_list[spu_cmd_count++] = "ROTH"
	spu_cmd_latency["ROTH"] = 4
	spu_cmd_pipe["ROTH"] = "even"
	spu_cmd_argv["ROTH", 0] = "wo"
	spu_cmd_argv["ROTH", 1] = "ro"
	spu_cmd_argv["ROTH", 2] = "ro"
	spu_cmd_argc["ROTH"] = 3
	spu_cmd_minc["ROTH"] = 3
	spu_cmd_maxc["ROTH"] = 3

	# Command: ROTHI
	spu_cmd_list[spu_cmd_count++] = "ROTHI"
	spu_cmd_latency["ROTHI"] = 4
	spu_cmd_pipe["ROTHI"] = "even"
	spu_cmd_argv["ROTHI", 0] = "wo"
	spu_cmd_argv["ROTHI", 1] = "ro"
	spu_cmd_argv["ROTHI", 2] = "im"
	spu_cmd_argc["ROTHI"] = 3
	spu_cmd_minc["ROTHI"] = 3
	spu_cmd_maxc["ROTHI"] = 3

	# Command: ROT
	spu_cmd_list[spu_cmd_count++] = "ROT"
	spu_cmd_latency["ROT"] = 4
	spu_cmd_pipe["ROT"] = "even"
	spu_cmd_argv["ROT", 0] = "wo"
	spu_cmd_argv["ROT", 1] = "ro"
	spu_cmd_argv["ROT", 2] = "ro"
	spu_cmd_argc["ROT"] = 3
	spu_cmd_minc["ROT"] = 3
	spu_cmd_maxc["ROT"] = 3

	# Command: ROTI
	spu_cmd_list[spu_cmd_count++] = "ROTI"
	spu_cmd_latency["ROTI"] = 4
	spu_cmd_pipe["ROTI"] = "even"
	spu_cmd_argv["ROTI", 0] = "wo"
	spu_cmd_argv["ROTI", 1] = "ro"
	spu_cmd_argv["ROTI", 2] = "im"
	spu_cmd_argc["ROTI"] = 3
	spu_cmd_minc["ROTI"] = 3
	spu_cmd_maxc["ROTI"] = 3

	# Command: ROTHM
	spu_cmd_list[spu_cmd_count++] = "ROTHM"
	spu_cmd_latency["ROTHM"] = 4
	spu_cmd_pipe["ROTHM"] = "even"
	spu_cmd_argv["ROTHM", 0] = "wo"
	spu_cmd_argv["ROTHM", 1] = "ro"
	spu_cmd_argv["ROTHM", 2] = "ro"
	spu_cmd_argc["ROTHM"] = 3
	spu_cmd_minc["ROTHM"] = 3
	spu_cmd_maxc["ROTHM"] = 3

	# Command: ROTHMI
	spu_cmd_list[spu_cmd_count++] = "ROTHMI"
	spu_cmd_latency["ROTHMI"] = 4
	spu_cmd_pipe["ROTHMI"] = "even"
	spu_cmd_argv["ROTHMI", 0] = "wo"
	spu_cmd_argv["ROTHMI", 1] = "ro"
	spu_cmd_argv["ROTHMI", 2] = "im"
	spu_cmd_argc["ROTHMI"] = 3
	spu_cmd_minc["ROTHMI"] = 3
	spu_cmd_maxc["ROTHMI"] = 3

	# Command: ROTM
	spu_cmd_list[spu_cmd_count++] = "ROTM"
	spu_cmd_latency["ROTM"] = 4
	spu_cmd_pipe["ROTM"] = "even"
	spu_cmd_argv["ROTM", 0] = "wo"
	spu_cmd_argv["ROTM", 1] = "ro"
	spu_cmd_argv["ROTM", 2] = "ro"
	spu_cmd_argc["ROTM"] = 3
	spu_cmd_minc["ROTM"] = 3
	spu_cmd_maxc["ROTM"] = 3

	# Command: ROTMI
	spu_cmd_list[spu_cmd_count++] = "ROTMI"
	spu_cmd_latency["ROTMI"] = 4
	spu_cmd_pipe["ROTMI"] = "even"
	spu_cmd_argv["ROTMI", 0] = "wo"
	spu_cmd_argv["ROTMI", 1] = "ro"
	spu_cmd_argv["ROTMI", 2] = "im"
	spu_cmd_argc["ROTMI"] = 3
	spu_cmd_minc["ROTMI"] = 3
	spu_cmd_maxc["ROTMI"] = 3

	# Command: ROTMAH
	spu_cmd_list[spu_cmd_count++] = "ROTMAH"
	spu_cmd_latency["ROTMAH"] = 4
	spu_cmd_pipe["ROTMAH"] = "even"
	spu_cmd_argv["ROTMAH", 0] = "wo"
	spu_cmd_argv["ROTMAH", 1] = "ro"
	spu_cmd_argv["ROTMAH", 2] = "ro"
	spu_cmd_argc["ROTMAH"] = 3
	spu_cmd_minc["ROTMAH"] = 3
	spu_cmd_maxc["ROTMAH"] = 3

	# Command: ROTMAHI
	spu_cmd_list[spu_cmd_count++] = "ROTMAHI"
	spu_cmd_latency["ROTMAHI"] = 4
	spu_cmd_pipe["ROTMAHI"] = "even"
	spu_cmd_argv["ROTMAHI", 0] = "wo"
	spu_cmd_argv["ROTMAHI", 1] = "ro"
	spu_cmd_argv["ROTMAHI", 2] = "im"
	spu_cmd_argc["ROTMAHI"] = 3
	spu_cmd_minc["ROTMAHI"] = 3
	spu_cmd_maxc["ROTMAHI"] = 3

	# Command: ROTMA
	spu_cmd_list[spu_cmd_count++] = "ROTMA"
	spu_cmd_latency["ROTMA"] = 4
	spu_cmd_pipe["ROTMA"] = "even"
	spu_cmd_argv["ROTMA", 0] = "wo"
	spu_cmd_argv["ROTMA", 1] = "ro"
	spu_cmd_argv["ROTMA", 2] = "ro"
	spu_cmd_argc["ROTMA"] = 3
	spu_cmd_minc["ROTMA"] = 3
	spu_cmd_maxc["ROTMA"] = 3

	# Command: ROTMAI
	spu_cmd_list[spu_cmd_count++] = "ROTMAI"
	spu_cmd_latency["ROTMAI"] = 4
	spu_cmd_pipe["ROTMAI"] = "even"
	spu_cmd_argv["ROTMAI", 0] = "wo"
	spu_cmd_argv["ROTMAI", 1] = "ro"
	spu_cmd_argv["ROTMAI", 2] = "im"
	spu_cmd_argc["ROTMAI"] = 3
	spu_cmd_minc["ROTMAI"] = 3
	spu_cmd_maxc["ROTMAI"] = 3

	# Command: MPY
	spu_cmd_list[spu_cmd_count++] = "MPY"
	spu_cmd_latency["MPY"] = 7
	spu_cmd_pipe["MPY"] = "even"
	spu_cmd_argv["MPY", 0] = "wo"
	spu_cmd_argv["MPY", 1] = "ro"
	spu_cmd_argv["MPY", 2] = "ro"
	spu_cmd_argc["MPY"] = 3
	spu_cmd_minc["MPY"] = 3
	spu_cmd_maxc["MPY"] = 3

	# Command: MPYI
	spu_cmd_list[spu_cmd_count++] = "MPYI"
	spu_cmd_latency["MPYI"] = 7
	spu_cmd_pipe["MPYI"] = "even"
	spu_cmd_argv["MPYI", 0] = "wo"
	spu_cmd_argv["MPYI", 1] = "ro"
	spu_cmd_argv["MPYI", 2] = "im"
	spu_cmd_argc["MPYI"] = 3
	spu_cmd_minc["MPYI"] = 3
	spu_cmd_maxc["MPYI"] = 3

	# Command: MPYU
	spu_cmd_list[spu_cmd_count++] = "MPYU"
	spu_cmd_latency["MPYU"] = 7
	spu_cmd_pipe["MPYU"] = "even"
	spu_cmd_argv["MPYU", 0] = "wo"
	spu_cmd_argv["MPYU", 1] = "ro"
	spu_cmd_argv["MPYU", 2] = "ro"
	spu_cmd_argc["MPYU"] = 3
	spu_cmd_minc["MPYU"] = 3
	spu_cmd_maxc["MPYU"] = 3

	# Command: MPYUI
	spu_cmd_list[spu_cmd_count++] = "MPYUI"
	spu_cmd_latency["MPYUI"] = 7
	spu_cmd_pipe["MPYUI"] = "even"
	spu_cmd_argv["MPYUI", 0] = "wo"
	spu_cmd_argv["MPYUI", 1] = "ro"
	spu_cmd_argv["MPYUI", 2] = "im"
	spu_cmd_argc["MPYUI"] = 3
	spu_cmd_minc["MPYUI"] = 3
	spu_cmd_maxc["MPYUI"] = 3

	# Command: MPYA
	spu_cmd_list[spu_cmd_count++] = "MPYA"
	spu_cmd_latency["MPYA"] = 7
	spu_cmd_pipe["MPYA"] = "even"
	spu_cmd_argv["MPYA", 0] = "wo"
	spu_cmd_argv["MPYA", 1] = "ro"
	spu_cmd_argv["MPYA", 2] = "ro"
	spu_cmd_argv["MPYA", 3] = "ro"
	spu_cmd_argc["MPYA"] = 4
	spu_cmd_minc["MPYA"] = 4
	spu_cmd_maxc["MPYA"] = 4

	# Command: MPYS
	spu_cmd_list[spu_cmd_count++] = "MPYS"
	spu_cmd_latency["MPYS"] = 7
	spu_cmd_pipe["MPYS"] = "even"
	spu_cmd_argv["MPYS", 0] = "wo"
	spu_cmd_argv["MPYS", 1] = "ro"
	spu_cmd_argv["MPYS", 2] = "ro"
	spu_cmd_argc["MPYS"] = 3
	spu_cmd_minc["MPYS"] = 3
	spu_cmd_maxc["MPYS"] = 3

	# Command: MPYH
	spu_cmd_list[spu_cmd_count++] = "MPYH"
	spu_cmd_latency["MPYH"] = 7
	spu_cmd_pipe["MPYH"] = "even"
	spu_cmd_argv["MPYH", 0] = "wo"
	spu_cmd_argv["MPYH", 1] = "ro"
	spu_cmd_argv["MPYH", 2] = "ro"
	spu_cmd_argc["MPYH"] = 3
	spu_cmd_minc["MPYH"] = 3
	spu_cmd_maxc["MPYH"] = 3

	# Command: MPYHH
	spu_cmd_list[spu_cmd_count++] = "MPYHH"
	spu_cmd_latency["MPYHH"] = 7
	spu_cmd_pipe["MPYHH"] = "even"
	spu_cmd_argv["MPYHH", 0] = "wo"
	spu_cmd_argv["MPYHH", 1] = "ro"
	spu_cmd_argv["MPYHH", 2] = "ro"
	spu_cmd_argc["MPYHH"] = 3
	spu_cmd_minc["MPYHH"] = 3
	spu_cmd_maxc["MPYHH"] = 3

	# Command: MPYHHU
	spu_cmd_list[spu_cmd_count++] = "MPYHHU"
	spu_cmd_latency["MPYHHU"] = 7
	spu_cmd_pipe["MPYHHU"] = "even"
	spu_cmd_argv["MPYHHU", 0] = "wo"
	spu_cmd_argv["MPYHHU", 1] = "ro"
	spu_cmd_argv["MPYHHU", 2] = "ro"
	spu_cmd_argc["MPYHHU"] = 3
	spu_cmd_minc["MPYHHU"] = 3
	spu_cmd_maxc["MPYHHU"] = 3

	# Command: MPYHHA
	spu_cmd_list[spu_cmd_count++] = "MPYHHA"
	spu_cmd_latency["MPYHHA"] = 7
	spu_cmd_pipe["MPYHHA"] = "even"
	spu_cmd_argv["MPYHHA", 0] = "wo"
	spu_cmd_argv["MPYHHA", 1] = "ro"
	spu_cmd_argv["MPYHHA", 2] = "ro"
	spu_cmd_argc["MPYHHA"] = 3
	spu_cmd_minc["MPYHHA"] = 3
	spu_cmd_maxc["MPYHHA"] = 3

	# Command: MPYHHAU
	spu_cmd_list[spu_cmd_count++] = "MPYHHAU"
	spu_cmd_latency["MPYHHAU"] = 7
	spu_cmd_pipe["MPYHHAU"] = "even"
	spu_cmd_argv["MPYHHAU", 0] = "wo"
	spu_cmd_argv["MPYHHAU", 1] = "ro"
	spu_cmd_argv["MPYHHAU", 2] = "ro"
	spu_cmd_argc["MPYHHAU"] = 3
	spu_cmd_minc["MPYHHAU"] = 3
	spu_cmd_maxc["MPYHHAU"] = 3

	# Command: FI
	spu_cmd_list[spu_cmd_count++] = "FI"
	spu_cmd_latency["FI"] = 7
	spu_cmd_pipe["FI"] = "even"
	spu_cmd_argv["FI", 0] = "wo"
	spu_cmd_argv["FI", 1] = "ro"
	spu_cmd_argv["FI", 2] = "ro"
	spu_cmd_argc["FI"] = 3
	spu_cmd_minc["FI"] = 3
	spu_cmd_maxc["FI"] = 3

	# Command: CUFLT
	spu_cmd_list[spu_cmd_count++] = "CUFLT"
	spu_cmd_latency["CUFLT"] = 7
	spu_cmd_pipe["CUFLT"] = "even"
	spu_cmd_argv["CUFLT", 0] = "wo"
	spu_cmd_argv["CUFLT", 1] = "ro"
	spu_cmd_argv["CUFLT", 2] = "im"
	spu_cmd_argc["CUFLT"] = 3
	spu_cmd_minc["CUFLT"] = 3
	spu_cmd_maxc["CUFLT"] = 3

	# Command: CSFLT
	spu_cmd_list[spu_cmd_count++] = "CSFLT"
	spu_cmd_latency["CSFLT"] = 7
	spu_cmd_pipe["CSFLT"] = "even"
	spu_cmd_argv["CSFLT", 0] = "wo"
	spu_cmd_argv["CSFLT", 1] = "ro"
	spu_cmd_argv["CSFLT", 2] = "im"
	spu_cmd_argc["CSFLT"] = 3
	spu_cmd_minc["CSFLT"] = 3
	spu_cmd_maxc["CSFLT"] = 3

	# Command: CFLTU
	spu_cmd_list[spu_cmd_count++] = "CFLTU"
	spu_cmd_latency["CFLTU"] = 7
	spu_cmd_pipe["CFLTU"] = "even"
	spu_cmd_argv["CFLTU", 0] = "wo"
	spu_cmd_argv["CFLTU", 1] = "ro"
	spu_cmd_argv["CFLTU", 2] = "im"
	spu_cmd_argc["CFLTU"] = 3
	spu_cmd_minc["CFLTU"] = 3
	spu_cmd_maxc["CFLTU"] = 3

	# Command: CFLTS
	spu_cmd_list[spu_cmd_count++] = "CFLTS"
	spu_cmd_latency["CFLTS"] = 7
	spu_cmd_pipe["CFLTS"] = "even"
	spu_cmd_argv["CFLTS", 0] = "wo"
	spu_cmd_argv["CFLTS", 1] = "ro"
	spu_cmd_argv["CFLTS", 2] = "im"
	spu_cmd_argc["CFLTS"] = 3
	spu_cmd_minc["CFLTS"] = 3
	spu_cmd_maxc["CFLTS"] = 3

	# Command: CEQB
	spu_cmd_list[spu_cmd_count++] = "CEQB"
	spu_cmd_latency["CEQB"] = 2
	spu_cmd_pipe["CEQB"] = "even"
	spu_cmd_argv["CEQB", 0] = "wo"
	spu_cmd_argv["CEQB", 1] = "ro"
	spu_cmd_argv["CEQB", 2] = "ro"
	spu_cmd_argc["CEQB"] = 3
	spu_cmd_minc["CEQB"] = 3
	spu_cmd_maxc["CEQB"] = 3

	# Command: CEQBI
	spu_cmd_list[spu_cmd_count++] = "CEQBI"
	spu_cmd_latency["CEQBI"] = 2
	spu_cmd_pipe["CEQBI"] = "even"
	spu_cmd_argv["CEQBI", 0] = "wo"
	spu_cmd_argv["CEQBI", 1] = "ro"
	spu_cmd_argv["CEQBI", 2] = "im"
	spu_cmd_argc["CEQBI"] = 3
	spu_cmd_minc["CEQBI"] = 3
	spu_cmd_maxc["CEQBI"] = 3

	# Command: CGTB
	spu_cmd_list[spu_cmd_count++] = "CGTB"
	spu_cmd_latency["CGTB"] = 2
	spu_cmd_pipe["CGTB"] = "even"
	spu_cmd_argv["CGTB", 0] = "wo"
	spu_cmd_argv["CGTB", 1] = "ro"
	spu_cmd_argv["CGTB", 2] = "ro"
	spu_cmd_argc["CGTB"] = 3
	spu_cmd_minc["CGTB"] = 3
	spu_cmd_maxc["CGTB"] = 3

	# Command: CGTBI
	spu_cmd_list[spu_cmd_count++] = "CGTBI"
	spu_cmd_latency["CGTBI"] = 2
	spu_cmd_pipe["CGTBI"] = "even"
	spu_cmd_argv["CGTBI", 0] = "wo"
	spu_cmd_argv["CGTBI", 1] = "ro"
	spu_cmd_argv["CGTBI", 2] = "im"
	spu_cmd_argc["CGTBI"] = 3
	spu_cmd_minc["CGTBI"] = 3
	spu_cmd_maxc["CGTBI"] = 3

	# Command: CLGTB
	spu_cmd_list[spu_cmd_count++] = "CLGTB"
	spu_cmd_latency["CLGTB"] = 2
	spu_cmd_pipe["CLGTB"] = "even"
	spu_cmd_argv["CLGTB", 0] = "wo"
	spu_cmd_argv["CLGTB", 1] = "ro"
	spu_cmd_argv["CLGTB", 2] = "ro"
	spu_cmd_argc["CLGTB"] = 3
	spu_cmd_minc["CLGTB"] = 3
	spu_cmd_maxc["CLGTB"] = 3

	# Command: CLGTBI
	spu_cmd_list[spu_cmd_count++] = "CLGTBI"
	spu_cmd_latency["CLGTBI"] = 2
	spu_cmd_pipe["CLGTBI"] = "even"
	spu_cmd_argv["CLGTBI", 0] = "wo"
	spu_cmd_argv["CLGTBI", 1] = "ro"
	spu_cmd_argv["CLGTBI", 2] = "im"
	spu_cmd_argc["CLGTBI"] = 3
	spu_cmd_minc["CLGTBI"] = 3
	spu_cmd_maxc["CLGTBI"] = 3

	# Command: CEQH
	spu_cmd_list[spu_cmd_count++] = "CEQH"
	spu_cmd_latency["CEQH"] = 2
	spu_cmd_pipe["CEQH"] = "even"
	spu_cmd_argv["CEQH", 0] = "wo"
	spu_cmd_argv["CEQH", 1] = "ro"
	spu_cmd_argv["CEQH", 2] = "ro"
	spu_cmd_argc["CEQH"] = 3
	spu_cmd_minc["CEQH"] = 3
	spu_cmd_maxc["CEQH"] = 3

	# Command: CEQHI
	spu_cmd_list[spu_cmd_count++] = "CEQHI"
	spu_cmd_latency["CEQHI"] = 2
	spu_cmd_pipe["CEQHI"] = "even"
	spu_cmd_argv["CEQHI", 0] = "wo"
	spu_cmd_argv["CEQHI", 1] = "ro"
	spu_cmd_argv["CEQHI", 2] = "im"
	spu_cmd_argc["CEQHI"] = 3
	spu_cmd_minc["CEQHI"] = 3
	spu_cmd_maxc["CEQHI"] = 3

	# Command: CGTH
	spu_cmd_list[spu_cmd_count++] = "CGTH"
	spu_cmd_latency["CGTH"] = 2
	spu_cmd_pipe["CGTH"] = "even"
	spu_cmd_argv["CGTH", 0] = "wo"
	spu_cmd_argv["CGTH", 1] = "ro"
	spu_cmd_argv["CGTH", 2] = "ro"
	spu_cmd_argc["CGTH"] = 3
	spu_cmd_minc["CGTH"] = 3
	spu_cmd_maxc["CGTH"] = 3

	# Command: CGTHI
	spu_cmd_list[spu_cmd_count++] = "CGTHI"
	spu_cmd_latency["CGTHI"] = 2
	spu_cmd_pipe["CGTHI"] = "even"
	spu_cmd_argv["CGTHI", 0] = "wo"
	spu_cmd_argv["CGTHI", 1] = "ro"
	spu_cmd_argv["CGTHI", 2] = "im"
	spu_cmd_argc["CGTHI"] = 3
	spu_cmd_minc["CGTHI"] = 3
	spu_cmd_maxc["CGTHI"] = 3

	# Command: CLGTH
	spu_cmd_list[spu_cmd_count++] = "CLGTH"
	spu_cmd_latency["CLGTH"] = 2
	spu_cmd_pipe["CLGTH"] = "even"
	spu_cmd_argv["CLGTH", 0] = "wo"
	spu_cmd_argv["CLGTH", 1] = "ro"
	spu_cmd_argv["CLGTH", 2] = "ro"
	spu_cmd_argc["CLGTH"] = 3
	spu_cmd_minc["CLGTH"] = 3
	spu_cmd_maxc["CLGTH"] = 3

	# Command: CLGTHI
	spu_cmd_list[spu_cmd_count++] = "CLGTHI"
	spu_cmd_latency["CLGTHI"] = 2
	spu_cmd_pipe["CLGTHI"] = "even"
	spu_cmd_argv["CLGTHI", 0] = "wo"
	spu_cmd_argv["CLGTHI", 1] = "ro"
	spu_cmd_argv["CLGTHI", 2] = "im"
	spu_cmd_argc["CLGTHI"] = 3
	spu_cmd_minc["CLGTHI"] = 3
	spu_cmd_maxc["CLGTHI"] = 3

	# Command: CEQ
	spu_cmd_list[spu_cmd_count++] = "CEQ"
	spu_cmd_latency["CEQ"] = 2
	spu_cmd_pipe["CEQ"] = "even"
	spu_cmd_argv["CEQ", 0] = "wo"
	spu_cmd_argv["CEQ", 1] = "ro"
	spu_cmd_argv["CEQ", 2] = "ro"
	spu_cmd_argc["CEQ"] = 3
	spu_cmd_minc["CEQ"] = 3
	spu_cmd_maxc["CEQ"] = 3

	# Command: CEQI
	spu_cmd_list[spu_cmd_count++] = "CEQI"
	spu_cmd_latency["CEQI"] = 2
	spu_cmd_pipe["CEQI"] = "even"
	spu_cmd_argv["CEQI", 0] = "wo"
	spu_cmd_argv["CEQI", 1] = "ro"
	spu_cmd_argv["CEQI", 2] = "im"
	spu_cmd_argc["CEQI"] = 3
	spu_cmd_minc["CEQI"] = 3
	spu_cmd_maxc["CEQI"] = 3

	# Command: CGT
	spu_cmd_list[spu_cmd_count++] = "CGT"
	spu_cmd_latency["CGT"] = 2
	spu_cmd_pipe["CGT"] = "even"
	spu_cmd_argv["CGT", 0] = "wo"
	spu_cmd_argv["CGT", 1] = "ro"
	spu_cmd_argv["CGT", 2] = "ro"
	spu_cmd_argc["CGT"] = 3
	spu_cmd_minc["CGT"] = 3
	spu_cmd_maxc["CGT"] = 3

	# Command: CGTI
	spu_cmd_list[spu_cmd_count++] = "CGTI"
	spu_cmd_latency["CGTI"] = 2
	spu_cmd_pipe["CGTI"] = "even"
	spu_cmd_argv["CGTI", 0] = "wo"
	spu_cmd_argv["CGTI", 1] = "ro"
	spu_cmd_argv["CGTI", 2] = "im"
	spu_cmd_argc["CGTI"] = 3
	spu_cmd_minc["CGTI"] = 3
	spu_cmd_maxc["CGTI"] = 3

	# Command: CLGT
	spu_cmd_list[spu_cmd_count++] = "CLGT"
	spu_cmd_latency["CLGT"] = 2
	spu_cmd_pipe["CLGT"] = "even"
	spu_cmd_argv["CLGT", 0] = "wo"
	spu_cmd_argv["CLGT", 1] = "ro"
	spu_cmd_argv["CLGT", 2] = "ro"
	spu_cmd_argc["CLGT"] = 3
	spu_cmd_minc["CLGT"] = 3
	spu_cmd_maxc["CLGT"] = 3

	# Command: CLGTI
	spu_cmd_list[spu_cmd_count++] = "CLGTI"
	spu_cmd_latency["CLGTI"] = 2
	spu_cmd_pipe["CLGTI"] = "even"
	spu_cmd_argv["CLGTI", 0] = "wo"
	spu_cmd_argv["CLGTI", 1] = "ro"
	spu_cmd_argv["CLGTI", 2] = "im"
	spu_cmd_argc["CLGTI"] = 3
	spu_cmd_minc["CLGTI"] = 3
	spu_cmd_maxc["CLGTI"] = 3

	# Command: FCEQ
	spu_cmd_list[spu_cmd_count++] = "FCEQ"
	spu_cmd_latency["FCEQ"] = 2
	spu_cmd_pipe["FCEQ"] = "even"
	spu_cmd_argv["FCEQ", 0] = "wo"
	spu_cmd_argv["FCEQ", 1] = "ro"
	spu_cmd_argv["FCEQ", 2] = "ro"
	spu_cmd_argc["FCEQ"] = 3
	spu_cmd_minc["FCEQ"] = 3
	spu_cmd_maxc["FCEQ"] = 3

	# Command: FCMEQ
	spu_cmd_list[spu_cmd_count++] = "FCMEQ"
	spu_cmd_latency["FCMEQ"] = 2
	spu_cmd_pipe["FCMEQ"] = "even"
	spu_cmd_argv["FCMEQ", 0] = "wo"
	spu_cmd_argv["FCMEQ", 1] = "ro"
	spu_cmd_argv["FCMEQ", 2] = "ro"
	spu_cmd_argc["FCMEQ"] = 3
	spu_cmd_minc["FCMEQ"] = 3
	spu_cmd_maxc["FCMEQ"] = 3

	# Command: FCGT
	spu_cmd_list[spu_cmd_count++] = "FCGT"
	spu_cmd_latency["FCGT"] = 2
	spu_cmd_pipe["FCGT"] = "even"
	spu_cmd_argv["FCGT", 0] = "wo"
	spu_cmd_argv["FCGT", 1] = "ro"
	spu_cmd_argv["FCGT", 2] = "ro"
	spu_cmd_argc["FCGT"] = 3
	spu_cmd_minc["FCGT"] = 3
	spu_cmd_maxc["FCGT"] = 3

	# Command: FCMGT
	spu_cmd_list[spu_cmd_count++] = "FCMGT"
	spu_cmd_latency["FCMGT"] = 2
	spu_cmd_pipe["FCMGT"] = "even"
	spu_cmd_argv["FCMGT", 0] = "wo"
	spu_cmd_argv["FCMGT", 1] = "ro"
	spu_cmd_argv["FCMGT", 2] = "ro"
	spu_cmd_argc["FCMGT"] = 3
	spu_cmd_minc["FCMGT"] = 3
	spu_cmd_maxc["FCMGT"] = 3

	# Command: AND
	spu_cmd_list[spu_cmd_count++] = "AND"
	spu_cmd_latency["AND"] = 2
	spu_cmd_pipe["AND"] = "even"
	spu_cmd_argv["AND", 0] = "wo"
	spu_cmd_argv["AND", 1] = "ro"
	spu_cmd_argv["AND", 2] = "ro"
	spu_cmd_argc["AND"] = 3
	spu_cmd_minc["AND"] = 3
	spu_cmd_maxc["AND"] = 3

	# Command: NAND
	spu_cmd_list[spu_cmd_count++] = "NAND"
	spu_cmd_latency["NAND"] = 2
	spu_cmd_pipe["NAND"] = "even"
	spu_cmd_argv["NAND", 0] = "wo"
	spu_cmd_argv["NAND", 1] = "ro"
	spu_cmd_argv["NAND", 2] = "ro"
	spu_cmd_argc["NAND"] = 3
	spu_cmd_minc["NAND"] = 3
	spu_cmd_maxc["NAND"] = 3

	# Command: ANDC
	spu_cmd_list[spu_cmd_count++] = "ANDC"
	spu_cmd_latency["ANDC"] = 2
	spu_cmd_pipe["ANDC"] = "even"
	spu_cmd_argv["ANDC", 0] = "wo"
	spu_cmd_argv["ANDC", 1] = "ro"
	spu_cmd_argv["ANDC", 2] = "ro"
	spu_cmd_argc["ANDC"] = 3
	spu_cmd_minc["ANDC"] = 3
	spu_cmd_maxc["ANDC"] = 3

	# Command: ANDBI
	spu_cmd_list[spu_cmd_count++] = "ANDBI"
	spu_cmd_latency["ANDBI"] = 2
	spu_cmd_pipe["ANDBI"] = "even"
	spu_cmd_argv["ANDBI", 0] = "wo"
	spu_cmd_argv["ANDBI", 1] = "ro"
	spu_cmd_argv["ANDBI", 2] = "im"
	spu_cmd_argc["ANDBI"] = 3
	spu_cmd_minc["ANDBI"] = 3
	spu_cmd_maxc["ANDBI"] = 3

	# Command: ANDHI
	spu_cmd_list[spu_cmd_count++] = "ANDHI"
	spu_cmd_latency["ANDHI"] = 2
	spu_cmd_pipe["ANDHI"] = "even"
	spu_cmd_argv["ANDHI", 0] = "wo"
	spu_cmd_argv["ANDHI", 1] = "ro"
	spu_cmd_argv["ANDHI", 2] = "im"
	spu_cmd_argc["ANDHI"] = 3
	spu_cmd_minc["ANDHI"] = 3
	spu_cmd_maxc["ANDHI"] = 3

	# Command: ANDI
	spu_cmd_list[spu_cmd_count++] = "ANDI"
	spu_cmd_latency["ANDI"] = 2
	spu_cmd_pipe["ANDI"] = "even"
	spu_cmd_argv["ANDI", 0] = "wo"
	spu_cmd_argv["ANDI", 1] = "ro"
	spu_cmd_argv["ANDI", 2] = "im"
	spu_cmd_argc["ANDI"] = 3
	spu_cmd_minc["ANDI"] = 3
	spu_cmd_maxc["ANDI"] = 3

	# Command: OR
	spu_cmd_list[spu_cmd_count++] = "OR"
	spu_cmd_latency["OR"] = 2
	spu_cmd_pipe["OR"] = "even"
	spu_cmd_argv["OR", 0] = "wo"
	spu_cmd_argv["OR", 1] = "ro"
	spu_cmd_argv["OR", 2] = "ro"
	spu_cmd_argc["OR"] = 3
	spu_cmd_minc["OR"] = 3
	spu_cmd_maxc["OR"] = 3

	# Command: NOR
	spu_cmd_list[spu_cmd_count++] = "NOR"
	spu_cmd_latency["NOR"] = 2
	spu_cmd_pipe["NOR"] = "even"
	spu_cmd_argv["NOR", 0] = "wo"
	spu_cmd_argv["NOR", 1] = "ro"
	spu_cmd_argv["NOR", 2] = "ro"
	spu_cmd_argc["NOR"] = 3
	spu_cmd_minc["NOR"] = 3
	spu_cmd_maxc["NOR"] = 3

	# Command: ORC
	spu_cmd_list[spu_cmd_count++] = "ORC"
	spu_cmd_latency["ORC"] = 2
	spu_cmd_pipe["ORC"] = "even"
	spu_cmd_argv["ORC", 0] = "wo"
	spu_cmd_argv["ORC", 1] = "ro"
	spu_cmd_argv["ORC", 2] = "ro"
	spu_cmd_argc["ORC"] = 3
	spu_cmd_minc["ORC"] = 3
	spu_cmd_maxc["ORC"] = 3

	# Command: ORBI
	spu_cmd_list[spu_cmd_count++] = "ORBI"
	spu_cmd_latency["ORBI"] = 2
	spu_cmd_pipe["ORBI"] = "even"
	spu_cmd_argv["ORBI", 0] = "wo"
	spu_cmd_argv["ORBI", 1] = "ro"
	spu_cmd_argv["ORBI", 2] = "im"
	spu_cmd_argc["ORBI"] = 3
	spu_cmd_minc["ORBI"] = 3
	spu_cmd_maxc["ORBI"] = 3

	# Command: ORHI
	spu_cmd_list[spu_cmd_count++] = "ORHI"
	spu_cmd_latency["ORHI"] = 2
	spu_cmd_pipe["ORHI"] = "even"
	spu_cmd_argv["ORHI", 0] = "wo"
	spu_cmd_argv["ORHI", 1] = "ro"
	spu_cmd_argv["ORHI", 2] = "im"
	spu_cmd_argc["ORHI"] = 3
	spu_cmd_minc["ORHI"] = 3
	spu_cmd_maxc["ORHI"] = 3

	# Command: ORI
	spu_cmd_list[spu_cmd_count++] = "ORI"
	spu_cmd_latency["ORI"] = 2
	spu_cmd_pipe["ORI"] = "even"
	spu_cmd_argv["ORI", 0] = "wo"
	spu_cmd_argv["ORI", 1] = "ro"
	spu_cmd_argv["ORI", 2] = "im"
	spu_cmd_argc["ORI"] = 3
	spu_cmd_minc["ORI"] = 3
	spu_cmd_maxc["ORI"] = 3

	# Command: XOR
	spu_cmd_list[spu_cmd_count++] = "XOR"
	spu_cmd_latency["XOR"] = 2
	spu_cmd_pipe["XOR"] = "even"
	spu_cmd_argv["XOR", 0] = "wo"
	spu_cmd_argv["XOR", 1] = "ro"
	spu_cmd_argv["XOR", 2] = "ro"
	spu_cmd_argc["XOR"] = 3
	spu_cmd_minc["XOR"] = 3
	spu_cmd_maxc["XOR"] = 3

	# Command: EQV
	spu_cmd_list[spu_cmd_count++] = "EQV"
	spu_cmd_latency["EQV"] = 2
	spu_cmd_pipe["EQV"] = "even"
	spu_cmd_argv["EQV", 0] = "wo"
	spu_cmd_argv["EQV", 1] = "ro"
	spu_cmd_argv["EQV", 2] = "ro"
	spu_cmd_argc["EQV"] = 3
	spu_cmd_minc["EQV"] = 3
	spu_cmd_maxc["EQV"] = 3

	# Command: XORBI
	spu_cmd_list[spu_cmd_count++] = "XORBI"
	spu_cmd_latency["XORBI"] = 2
	spu_cmd_pipe["XORBI"] = "even"
	spu_cmd_argv["XORBI", 0] = "wo"
	spu_cmd_argv["XORBI", 1] = "ro"
	spu_cmd_argv["XORBI", 2] = "im"
	spu_cmd_argc["XORBI"] = 3
	spu_cmd_minc["XORBI"] = 3
	spu_cmd_maxc["XORBI"] = 3

	# Command: XORHI
	spu_cmd_list[spu_cmd_count++] = "XORHI"
	spu_cmd_latency["XORHI"] = 2
	spu_cmd_pipe["XORHI"] = "even"
	spu_cmd_argv["XORHI", 0] = "wo"
	spu_cmd_argv["XORHI", 1] = "ro"
	spu_cmd_argv["XORHI", 2] = "im"
	spu_cmd_argc["XORHI"] = 3
	spu_cmd_minc["XORHI"] = 3
	spu_cmd_maxc["XORHI"] = 3

	# Command: XORI
	spu_cmd_list[spu_cmd_count++] = "XORI"
	spu_cmd_latency["XORI"] = 2
	spu_cmd_pipe["XORI"] = "even"
	spu_cmd_argv["XORI", 0] = "wo"
	spu_cmd_argv["XORI", 1] = "ro"
	spu_cmd_argv["XORI", 2] = "im"
	spu_cmd_argc["XORI"] = 3
	spu_cmd_minc["XORI"] = 3
	spu_cmd_maxc["XORI"] = 3

	# Command: IL
	spu_cmd_list[spu_cmd_count++] = "IL"
	spu_cmd_latency["IL"] = 2
	spu_cmd_pipe["IL"] = "even"
	spu_cmd_argv["IL", 0] = "wo"
	spu_cmd_argv["IL", 1] = "im"
	spu_cmd_argc["IL"] = 2
	spu_cmd_minc["IL"] = 2
	spu_cmd_maxc["IL"] = 2

	# Command: ILH
	spu_cmd_list[spu_cmd_count++] = "ILH"
	spu_cmd_latency["ILH"] = 2
	spu_cmd_pipe["ILH"] = "even"
	spu_cmd_argv["ILH", 0] = "wo"
	spu_cmd_argv["ILH", 1] = "im"
	spu_cmd_argc["ILH"] = 2
	spu_cmd_minc["ILH"] = 2
	spu_cmd_maxc["ILH"] = 2

	# Command: ILA
	spu_cmd_list[spu_cmd_count++] = "ILA"
	spu_cmd_latency["ILA"] = 2
	spu_cmd_pipe["ILA"] = "even"
	spu_cmd_argv["ILA", 0] = "wo"
	spu_cmd_argv["ILA", 1] = "im"
	spu_cmd_argc["ILA"] = 2
	spu_cmd_minc["ILA"] = 2
	spu_cmd_maxc["ILA"] = 2

	# Command: ILHU
	spu_cmd_list[spu_cmd_count++] = "ILHU"
	spu_cmd_latency["ILHU"] = 2
	spu_cmd_pipe["ILHU"] = "even"
	spu_cmd_argv["ILHU", 0] = "wo"
	spu_cmd_argv["ILHU", 1] = "im"
	spu_cmd_argc["ILHU"] = 2
	spu_cmd_minc["ILHU"] = 2
	spu_cmd_maxc["ILHU"] = 2

	# Command: IOHL
	spu_cmd_list[spu_cmd_count++] = "IOHL"
	spu_cmd_latency["IOHL"] = 2
	spu_cmd_pipe["IOHL"] = "even"
	spu_cmd_argv["IOHL", 0] = "wo"
	spu_cmd_argv["IOHL", 1] = "im"
	spu_cmd_argc["IOHL"] = 2
	spu_cmd_minc["IOHL"] = 2
	spu_cmd_maxc["IOHL"] = 2

	# Command: AH
	spu_cmd_list[spu_cmd_count++] = "AH"
	spu_cmd_latency["AH"] = 2
	spu_cmd_pipe["AH"] = "even"
	spu_cmd_argv["AH", 0] = "wo"
	spu_cmd_argv["AH", 1] = "ro"
	spu_cmd_argv["AH", 2] = "ro"
	spu_cmd_argc["AH"] = 3
	spu_cmd_minc["AH"] = 3
	spu_cmd_maxc["AH"] = 3

	# Command: AHI
	spu_cmd_list[spu_cmd_count++] = "AHI"
	spu_cmd_latency["AHI"] = 2
	spu_cmd_pipe["AHI"] = "even"
	spu_cmd_argv["AHI", 0] = "wo"
	spu_cmd_argv["AHI", 1] = "ro"
	spu_cmd_argv["AHI", 2] = "im"
	spu_cmd_argc["AHI"] = 3
	spu_cmd_minc["AHI"] = 3
	spu_cmd_maxc["AHI"] = 3

	# Command: A
	spu_cmd_list[spu_cmd_count++] = "A"
	spu_cmd_latency["A"] = 2
	spu_cmd_pipe["A"] = "even"
	spu_cmd_argv["A", 0] = "wo"
	spu_cmd_argv["A", 1] = "ro"
	spu_cmd_argv["A", 2] = "ro"
	spu_cmd_argc["A"] = 3
	spu_cmd_minc["A"] = 3
	spu_cmd_maxc["A"] = 3

	# Command: AI
	spu_cmd_list[spu_cmd_count++] = "AI"
	spu_cmd_latency["AI"] = 2
	spu_cmd_pipe["AI"] = "even"
	spu_cmd_argv["AI", 0] = "wo"
	spu_cmd_argv["AI", 1] = "ro"
	spu_cmd_argv["AI", 2] = "im"
	spu_cmd_argc["AI"] = 3
	spu_cmd_minc["AI"] = 3
	spu_cmd_maxc["AI"] = 3

	# Command: SFH
	spu_cmd_list[spu_cmd_count++] = "SFH"
	spu_cmd_latency["SFH"] = 2
	spu_cmd_pipe["SFH"] = "even"
	spu_cmd_argv["SFH", 0] = "wo"
	spu_cmd_argv["SFH", 1] = "ro"
	spu_cmd_argv["SFH", 2] = "ro"
	spu_cmd_argc["SFH"] = 3
	spu_cmd_minc["SFH"] = 3
	spu_cmd_maxc["SFH"] = 3

	# Command: SFHI
	spu_cmd_list[spu_cmd_count++] = "SFHI"
	spu_cmd_latency["SFHI"] = 2
	spu_cmd_pipe["SFHI"] = "even"
	spu_cmd_argv["SFHI", 0] = "wo"
	spu_cmd_argv["SFHI", 1] = "ro"
	spu_cmd_argv["SFHI", 2] = "im"
	spu_cmd_argc["SFHI"] = 3
	spu_cmd_minc["SFHI"] = 3
	spu_cmd_maxc["SFHI"] = 3

	# Command: SF
	spu_cmd_list[spu_cmd_count++] = "SF"
	spu_cmd_latency["SF"] = 2
	spu_cmd_pipe["SF"] = "even"
	spu_cmd_argv["SF", 0] = "wo"
	spu_cmd_argv["SF", 1] = "ro"
	spu_cmd_argv["SF", 2] = "ro"
	spu_cmd_argc["SF"] = 3
	spu_cmd_minc["SF"] = 3
	spu_cmd_maxc["SF"] = 3

	# Command: SFI
	spu_cmd_list[spu_cmd_count++] = "SFI"
	spu_cmd_latency["SFI"] = 2
	spu_cmd_pipe["SFI"] = "even"
	spu_cmd_argv["SFI", 0] = "wo"
	spu_cmd_argv["SFI", 1] = "ro"
	spu_cmd_argv["SFI", 2] = "im"
	spu_cmd_argc["SFI"] = 3
	spu_cmd_minc["SFI"] = 3
	spu_cmd_maxc["SFI"] = 3

	# Command: BG
	spu_cmd_list[spu_cmd_count++] = "BG"
	spu_cmd_latency["BG"] = 2
	spu_cmd_pipe["BG"] = "even"
	spu_cmd_argv["BG", 0] = "wo"
	spu_cmd_argv["BG", 1] = "ro"
	spu_cmd_argv["BG", 2] = "ro"
	spu_cmd_argc["BG"] = 3
	spu_cmd_minc["BG"] = 3
	spu_cmd_maxc["BG"] = 3

	# Command: BGX
	spu_cmd_list[spu_cmd_count++] = "BGX"
	spu_cmd_latency["BGX"] = 2
	spu_cmd_pipe["BGX"] = "even"
	spu_cmd_argv["BGX", 0] = "rw"
	spu_cmd_argv["BGX", 1] = "ro"
	spu_cmd_argv["BGX", 2] = "ro"
	spu_cmd_argc["BGX"] = 3
	spu_cmd_minc["BGX"] = 3
	spu_cmd_maxc["BGX"] = 3

	# Command: SFX
	spu_cmd_list[spu_cmd_count++] = "SFX"
	spu_cmd_latency["SFX"] = 2
	spu_cmd_pipe["SFX"] = "even"
	spu_cmd_argv["SFX", 0] = "rw"
	spu_cmd_argv["SFX", 1] = "ro"
	spu_cmd_argv["SFX", 2] = "ro"
	spu_cmd_argc["SFX"] = 3
	spu_cmd_minc["SFX"] = 3
	spu_cmd_maxc["SFX"] = 3

	# Command: CG
	spu_cmd_list[spu_cmd_count++] = "CG"
	spu_cmd_latency["CG"] = 2
	spu_cmd_pipe["CG"] = "even"
	spu_cmd_argv["CG", 0] = "wo"
	spu_cmd_argv["CG", 1] = "ro"
	spu_cmd_argv["CG", 2] = "ro"
	spu_cmd_argc["CG"] = 3
	spu_cmd_minc["CG"] = 3
	spu_cmd_maxc["CG"] = 3

	# Command: CGX
	spu_cmd_list[spu_cmd_count++] = "CGX"
	spu_cmd_latency["CGX"] = 2
	spu_cmd_pipe["CGX"] = "even"
	spu_cmd_argv["CGX", 0] = "rw"
	spu_cmd_argv["CGX", 1] = "ro"
	spu_cmd_argv["CGX", 2] = "ro"
	spu_cmd_argc["CGX"] = 3
	spu_cmd_minc["CGX"] = 3
	spu_cmd_maxc["CGX"] = 3

	# Command: ADDX
	spu_cmd_list[spu_cmd_count++] = "ADDX"
	spu_cmd_latency["ADDX"] = 2
	spu_cmd_pipe["ADDX"] = "even"
	spu_cmd_argv["ADDX", 0] = "rw"
	spu_cmd_argv["ADDX", 1] = "ro"
	spu_cmd_argv["ADDX", 2] = "ro"
	spu_cmd_argc["ADDX"] = 3
	spu_cmd_minc["ADDX"] = 3
	spu_cmd_maxc["ADDX"] = 3

	# Command: XSBH
	spu_cmd_list[spu_cmd_count++] = "XSBH"
	spu_cmd_latency["XSBH"] = 2
	spu_cmd_pipe["XSBH"] = "even"
	spu_cmd_argv["XSBH", 0] = "wo"
	spu_cmd_argv["XSBH", 1] = "ro"
	spu_cmd_argc["XSBH"] = 2
	spu_cmd_minc["XSBH"] = 2
	spu_cmd_maxc["XSBH"] = 2

	# Command: XSHW
	spu_cmd_list[spu_cmd_count++] = "XSHW"
	spu_cmd_latency["XSHW"] = 2
	spu_cmd_pipe["XSHW"] = "even"
	spu_cmd_argv["XSHW", 0] = "wo"
	spu_cmd_argv["XSHW", 1] = "ro"
	spu_cmd_argc["XSHW"] = 2
	spu_cmd_minc["XSHW"] = 2
	spu_cmd_maxc["XSHW"] = 2

	# Command: XSWD
	spu_cmd_list[spu_cmd_count++] = "XSWD"
	spu_cmd_latency["XSWD"] = 2
	spu_cmd_pipe["XSWD"] = "even"
	spu_cmd_argv["XSWD", 0] = "wo"
	spu_cmd_argv["XSWD", 1] = "ro"
	spu_cmd_argc["XSWD"] = 2
	spu_cmd_minc["XSWD"] = 2
	spu_cmd_maxc["XSWD"] = 2

	# Command: CLZ
	spu_cmd_list[spu_cmd_count++] = "CLZ"
	spu_cmd_latency["CLZ"] = 2
	spu_cmd_pipe["CLZ"] = "even"
	spu_cmd_argv["CLZ", 0] = "wo"
	spu_cmd_argv["CLZ", 1] = "ro"
	spu_cmd_argc["CLZ"] = 2
	spu_cmd_minc["CLZ"] = 2
	spu_cmd_maxc["CLZ"] = 2

	# Command: SELB
	spu_cmd_list[spu_cmd_count++] = "SELB"
	spu_cmd_latency["SELB"] = 2
	spu_cmd_pipe["SELB"] = "even"
	spu_cmd_argv["SELB", 0] = "wo"
	spu_cmd_argv["SELB", 1] = "ro"
	spu_cmd_argv["SELB", 2] = "ro"
	spu_cmd_argv["SELB", 3] = "ro"
	spu_cmd_argc["SELB"] = 4
	spu_cmd_minc["SELB"] = 4
	spu_cmd_maxc["SELB"] = 4

	# Command: SYNC
	spu_cmd_list[spu_cmd_count++] = "SYNC"
	spu_cmd_latency["SYNC"] = 1
	spu_cmd_pipe["SYNC"] = "even"
	spu_cmd_argc["SYNC"] = 0
	spu_cmd_minc["SYNC"] = 0
	spu_cmd_maxc["SYNC"] = 0

	# Command: SYNCC
	spu_cmd_list[spu_cmd_count++] = "SYNCC"
	spu_cmd_latency["SYNCC"] = 1
	spu_cmd_pipe["SYNCC"] = "even"
	spu_cmd_argc["SYNCC"] = 0
	spu_cmd_minc["SYNCC"] = 0
	spu_cmd_maxc["SYNCC"] = 0

	# Command: DSYNC
	spu_cmd_list[spu_cmd_count++] = "DSYNC"
	spu_cmd_latency["DSYNC"] = 1
	spu_cmd_pipe["DSYNC"] = "even"
	spu_cmd_argc["DSYNC"] = 0
	spu_cmd_minc["DSYNC"] = 0
	spu_cmd_maxc["DSYNC"] = 0

	# Command: LNOP
	spu_cmd_list[spu_cmd_count++] = "LNOP"
	spu_cmd_latency["LNOP"] = 1
	spu_cmd_pipe["LNOP"] = "odd"
	spu_cmd_argv["LNOP", 0] = "!rw"
	spu_cmd_argc["LNOP"] = 0
	spu_cmd_minc["LNOP"] = 0
	spu_cmd_maxc["LNOP"] = 1

	# Command: BR
	spu_cmd_list[spu_cmd_count++] = "BR"
	spu_cmd_latency["BR"] = 1
	spu_cmd_pipe["BR"] = "odd"
	spu_cmd_argv["BR", 0] = "br"
	spu_cmd_argc["BR"] = 1
	spu_cmd_minc["BR"] = 1
	spu_cmd_maxc["BR"] = 1

	# Command: BRSL
	spu_cmd_list[spu_cmd_count++] = "BRSL"
	spu_cmd_latency["BRSL"] = 4
	spu_cmd_pipe["BRSL"] = "odd"
	spu_cmd_argv["BRSL", 0] = "ro"
	spu_cmd_argv["BRSL", 1] = "br"
	spu_cmd_argc["BRSL"] = 2
	spu_cmd_minc["BRSL"] = 2
	spu_cmd_maxc["BRSL"] = 2

	# Command: BRHNZ
	spu_cmd_list[spu_cmd_count++] = "BRHNZ"
	spu_cmd_latency["BRHNZ"] = 1
	spu_cmd_pipe["BRHNZ"] = "odd"
	spu_cmd_argv["BRHNZ", 0] = "ro"
	spu_cmd_argv["BRHNZ", 1] = "br"
	spu_cmd_argc["BRHNZ"] = 2
	spu_cmd_minc["BRHNZ"] = 2
	spu_cmd_maxc["BRHNZ"] = 2

	# Command: BRHZ
	spu_cmd_list[spu_cmd_count++] = "BRHZ"
	spu_cmd_latency["BRHZ"] = 1
	spu_cmd_pipe["BRHZ"] = "odd"
	spu_cmd_argv["BRHZ", 0] = "ro"
	spu_cmd_argv["BRHZ", 1] = "br"
	spu_cmd_argc["BRHZ"] = 2
	spu_cmd_minc["BRHZ"] = 2
	spu_cmd_maxc["BRHZ"] = 2

	# Command: BRNZ
	spu_cmd_list[spu_cmd_count++] = "BRNZ"
	spu_cmd_latency["BRNZ"] = 1
	spu_cmd_pipe["BRNZ"] = "odd"
	spu_cmd_argv["BRNZ", 0] = "ro"
	spu_cmd_argv["BRNZ", 1] = "br"
	spu_cmd_argc["BRNZ"] = 2
	spu_cmd_minc["BRNZ"] = 2
	spu_cmd_maxc["BRNZ"] = 2

	# Command: BRZ
	spu_cmd_list[spu_cmd_count++] = "BRZ"
	spu_cmd_latency["BRZ"] = 1
	spu_cmd_pipe["BRZ"] = "odd"
	spu_cmd_argv["BRZ", 0] = "ro"
	spu_cmd_argv["BRZ", 1] = "br"
	spu_cmd_argc["BRZ"] = 2
	spu_cmd_minc["BRZ"] = 2
	spu_cmd_maxc["BRZ"] = 2

	# Command: BI
	spu_cmd_list[spu_cmd_count++] = "BI"
	spu_cmd_latency["BI"] = 1
	spu_cmd_pipe["BI"] = "odd"
	spu_cmd_argv["BI", 0] = "ro"
	spu_cmd_argc["BI"] = 1
	spu_cmd_minc["BI"] = 1
	spu_cmd_maxc["BI"] = 1

	# Command: BID
	spu_cmd_list[spu_cmd_count++] = "BID"
	spu_cmd_latency["BID"] = 1
	spu_cmd_pipe["BID"] = "odd"
	spu_cmd_argv["BID", 0] = "ro"
	spu_cmd_argc["BID"] = 1
	spu_cmd_minc["BID"] = 1
	spu_cmd_maxc["BID"] = 1

	# Command: BIE
	spu_cmd_list[spu_cmd_count++] = "BIE"
	spu_cmd_latency["BIE"] = 1
	spu_cmd_pipe["BIE"] = "odd"
	spu_cmd_argv["BIE", 0] = "ro"
	spu_cmd_argc["BIE"] = 1
	spu_cmd_minc["BIE"] = 1
	spu_cmd_maxc["BIE"] = 1

	# Command: BISL
	spu_cmd_list[spu_cmd_count++] = "BISL"
	spu_cmd_latency["BISL"] = 4
	spu_cmd_pipe["BISL"] = "odd"
	spu_cmd_argv["BISL", 0] = "wo"
	spu_cmd_argv["BISL", 1] = "ro"
	spu_cmd_argc["BISL"] = 2
	spu_cmd_minc["BISL"] = 2
	spu_cmd_maxc["BISL"] = 2

	# Command: BISLED
	spu_cmd_list[spu_cmd_count++] = "BISLED"
	spu_cmd_latency["BISLED"] = 4
	spu_cmd_pipe["BISLED"] = "odd"
	spu_cmd_argv["BISLED", 0] = "wo"
	spu_cmd_argv["BISLED", 1] = "ro"
	spu_cmd_argc["BISLED"] = 2
	spu_cmd_minc["BISLED"] = 2
	spu_cmd_maxc["BISLED"] = 2

	# Command: BIHNZ
	spu_cmd_list[spu_cmd_count++] = "BIHNZ"
	spu_cmd_latency["BIHNZ"] = 1
	spu_cmd_pipe["BIHNZ"] = "odd"
	spu_cmd_argv["BIHNZ", 0] = "ro"
	spu_cmd_argv["BIHNZ", 1] = "ro"
	spu_cmd_argc["BIHNZ"] = 2
	spu_cmd_minc["BIHNZ"] = 2
	spu_cmd_maxc["BIHNZ"] = 2

	# Command: BIHZ
	spu_cmd_list[spu_cmd_count++] = "BIHZ"
	spu_cmd_latency["BIHZ"] = 1
	spu_cmd_pipe["BIHZ"] = "odd"
	spu_cmd_argv["BIHZ", 0] = "ro"
	spu_cmd_argv["BIHZ", 1] = "ro"
	spu_cmd_argc["BIHZ"] = 2
	spu_cmd_minc["BIHZ"] = 2
	spu_cmd_maxc["BIHZ"] = 2

	# Command: BIHZE
	spu_cmd_list[spu_cmd_count++] = "BIHZE"
	spu_cmd_latency["BIHZE"] = 1
	spu_cmd_pipe["BIHZE"] = "odd"
	spu_cmd_argv["BIHZE", 0] = "ro"
	spu_cmd_argv["BIHZE", 1] = "ro"
	spu_cmd_argc["BIHZE"] = 2
	spu_cmd_minc["BIHZE"] = 2
	spu_cmd_maxc["BIHZE"] = 2

	# Command: BINZ
	spu_cmd_list[spu_cmd_count++] = "BINZ"
	spu_cmd_latency["BINZ"] = 1
	spu_cmd_pipe["BINZ"] = "odd"
	spu_cmd_argv["BINZ", 0] = "ro"
	spu_cmd_argv["BINZ", 1] = "ro"
	spu_cmd_argc["BINZ"] = 2
	spu_cmd_minc["BINZ"] = 2
	spu_cmd_maxc["BINZ"] = 2

	# Command: BIZ
	spu_cmd_list[spu_cmd_count++] = "BIZ"
	spu_cmd_latency["BIZ"] = 1
	spu_cmd_pipe["BIZ"] = "odd"
	spu_cmd_argv["BIZ", 0] = "ro"
	spu_cmd_argv["BIZ", 1] = "ro"
	spu_cmd_argc["BIZ"] = 2
	spu_cmd_minc["BIZ"] = 2
	spu_cmd_maxc["BIZ"] = 2

	# Command: BRA
	spu_cmd_list[spu_cmd_count++] = "BRA"
	spu_cmd_latency["BRA"] = 1
	spu_cmd_pipe["BRA"] = "odd"
	spu_cmd_argv["BRA", 0] = "br"
	spu_cmd_argc["BRA"] = 1
	spu_cmd_minc["BRA"] = 1
	spu_cmd_maxc["BRA"] = 1

	# Command: BRASL
	spu_cmd_list[spu_cmd_count++] = "BRASL"
	spu_cmd_latency["BRASL"] = 4
	spu_cmd_pipe["BRASL"] = "odd"
	spu_cmd_argv["BRASL", 0] = "wo"
	spu_cmd_argv["BRASL", 1] = "br"
	spu_cmd_argc["BRASL"] = 2
	spu_cmd_minc["BRASL"] = 2
	spu_cmd_maxc["BRASL"] = 2

	# Command: HBR
	spu_cmd_list[spu_cmd_count++] = "HBR"
	spu_cmd_latency["HBR"] = 15
	spu_cmd_pipe["HBR"] = "odd"
	spu_cmd_argv["HBR", 0] = "br"
	spu_cmd_argv["HBR", 1] = "ro"
	spu_cmd_argc["HBR"] = 2
	spu_cmd_minc["HBR"] = 2
	spu_cmd_maxc["HBR"] = 2

	# Command: HBRA
	spu_cmd_list[spu_cmd_count++] = "HBRA"
	spu_cmd_latency["HBRA"] = 15
	spu_cmd_pipe["HBRA"] = "odd"
	spu_cmd_argv["HBRA", 0] = "br"
	spu_cmd_argv["HBRA", 1] = "br"
	spu_cmd_argc["HBRA"] = 2
	spu_cmd_minc["HBRA"] = 2
	spu_cmd_maxc["HBRA"] = 2

	# Command: HBRR
	spu_cmd_list[spu_cmd_count++] = "HBRR"
	spu_cmd_latency["HBRR"] = 15
	spu_cmd_pipe["HBRR"] = "odd"
	spu_cmd_argv["HBRR", 0] = "br"
	spu_cmd_argv["HBRR", 1] = "br"
	spu_cmd_argc["HBRR"] = 2
	spu_cmd_minc["HBRR"] = 2
	spu_cmd_maxc["HBRR"] = 2

	# Command: HBRP
	spu_cmd_list[spu_cmd_count++] = "HBRP"
	spu_cmd_latency["HBRP"] = 15
	spu_cmd_pipe["HBRP"] = "odd"
	spu_cmd_argv["HBRP", 0] = "br"
	spu_cmd_argv["HBRP", 1] = "ro"
	spu_cmd_argc["HBRP"] = 2
	spu_cmd_minc["HBRP"] = 2
	spu_cmd_maxc["HBRP"] = 2

	# Command: LQA
	spu_cmd_list[spu_cmd_count++] = "LQA"
	spu_cmd_latency["LQA"] = 6
	spu_cmd_pipe["LQA"] = "odd"
	spu_cmd_argv["LQA", 0] = "wo"
	spu_cmd_argv["LQA", 1] = "lb"
	spu_cmd_argc["LQA"] = 2
	spu_cmd_minc["LQA"] = 2
	spu_cmd_maxc["LQA"] = 2

	# Command: LQD
	spu_cmd_list[spu_cmd_count++] = "LQD"
	spu_cmd_latency["LQD"] = 6
	spu_cmd_pipe["LQD"] = "odd"
	spu_cmd_argv["LQD", 0] = "wo"
	spu_cmd_argv["LQD", 1] = "ir"
	spu_cmd_argc["LQD"] = 2
	spu_cmd_minc["LQD"] = 2
	spu_cmd_maxc["LQD"] = 2

	# Command: LQR
	spu_cmd_list[spu_cmd_count++] = "LQR"
	spu_cmd_latency["LQR"] = 6
	spu_cmd_pipe["LQR"] = "odd"
	spu_cmd_argv["LQR", 0] = "wo"
	spu_cmd_argv["LQR", 1] = "lb"
	spu_cmd_argc["LQR"] = 2
	spu_cmd_minc["LQR"] = 2
	spu_cmd_maxc["LQR"] = 2

	# Command: LQX
	spu_cmd_list[spu_cmd_count++] = "LQX"
	spu_cmd_latency["LQX"] = 6
	spu_cmd_pipe["LQX"] = "odd"
	spu_cmd_argv["LQX", 0] = "wo"
	spu_cmd_argv["LQX", 1] = "ro"
	spu_cmd_argv["LQX", 2] = "ro"
	spu_cmd_argc["LQX"] = 3
	spu_cmd_minc["LQX"] = 3
	spu_cmd_maxc["LQX"] = 3

	# Command: STQA
	spu_cmd_list[spu_cmd_count++] = "STQA"
	spu_cmd_latency["STQA"] = 1
	spu_cmd_pipe["STQA"] = "odd"
	spu_cmd_argv["STQA", 0] = "ro"
	spu_cmd_argv["STQA", 1] = "lb"
	spu_cmd_argc["STQA"] = 2
	spu_cmd_minc["STQA"] = 2
	spu_cmd_maxc["STQA"] = 2

	# Command: STQD
	spu_cmd_list[spu_cmd_count++] = "STQD"
	spu_cmd_latency["STQD"] = 1
	spu_cmd_pipe["STQD"] = "odd"
	spu_cmd_argv["STQD", 0] = "ro"
	spu_cmd_argv["STQD", 1] = "ir"
	spu_cmd_argc["STQD"] = 2
	spu_cmd_minc["STQD"] = 2
	spu_cmd_maxc["STQD"] = 2

	# Command: STQR
	spu_cmd_list[spu_cmd_count++] = "STQR"
	spu_cmd_latency["STQR"] = 1
	spu_cmd_pipe["STQR"] = "odd"
	spu_cmd_argv["STQR", 0] = "ro"
	spu_cmd_argv["STQR", 1] = "lb"
	spu_cmd_argc["STQR"] = 2
	spu_cmd_minc["STQR"] = 2
	spu_cmd_maxc["STQR"] = 2

	# Command: STQX
	spu_cmd_list[spu_cmd_count++] = "STQX"
	spu_cmd_latency["STQX"] = 1
	spu_cmd_pipe["STQX"] = "odd"
	spu_cmd_argv["STQX", 0] = "ro"
	spu_cmd_argv["STQX", 1] = "ro"
	spu_cmd_argv["STQX", 2] = "ro"
	spu_cmd_argc["STQX"] = 3
	spu_cmd_minc["STQX"] = 3
	spu_cmd_maxc["STQX"] = 3

	# Command: SHLQBY
	spu_cmd_list[spu_cmd_count++] = "SHLQBY"
	spu_cmd_latency["SHLQBY"] = 4
	spu_cmd_pipe["SHLQBY"] = "odd"
	spu_cmd_argv["SHLQBY", 0] = "wo"
	spu_cmd_argv["SHLQBY", 1] = "ro"
	spu_cmd_argv["SHLQBY", 2] = "ro"
	spu_cmd_argc["SHLQBY"] = 3
	spu_cmd_minc["SHLQBY"] = 3
	spu_cmd_maxc["SHLQBY"] = 3

	# Command: SHLQBYI
	spu_cmd_list[spu_cmd_count++] = "SHLQBYI"
	spu_cmd_latency["SHLQBYI"] = 4
	spu_cmd_pipe["SHLQBYI"] = "odd"
	spu_cmd_argv["SHLQBYI", 0] = "wo"
	spu_cmd_argv["SHLQBYI", 1] = "ro"
	spu_cmd_argv["SHLQBYI", 2] = "im"
	spu_cmd_argc["SHLQBYI"] = 3
	spu_cmd_minc["SHLQBYI"] = 3
	spu_cmd_maxc["SHLQBYI"] = 3

	# Command: SHLQBYBI
	spu_cmd_list[spu_cmd_count++] = "SHLQBYBI"
	spu_cmd_latency["SHLQBYBI"] = 4
	spu_cmd_pipe["SHLQBYBI"] = "odd"
	spu_cmd_argv["SHLQBYBI", 0] = "wo"
	spu_cmd_argv["SHLQBYBI", 1] = "ro"
	spu_cmd_argv["SHLQBYBI", 2] = "ro"
	spu_cmd_argc["SHLQBYBI"] = 3
	spu_cmd_minc["SHLQBYBI"] = 3
	spu_cmd_maxc["SHLQBYBI"] = 3

	# Command: SHLQBI
	spu_cmd_list[spu_cmd_count++] = "SHLQBI"
	spu_cmd_latency["SHLQBI"] = 4
	spu_cmd_pipe["SHLQBI"] = "odd"
	spu_cmd_argv["SHLQBI", 0] = "wo"
	spu_cmd_argv["SHLQBI", 1] = "ro"
	spu_cmd_argv["SHLQBI", 2] = "ro"
	spu_cmd_argc["SHLQBI"] = 3
	spu_cmd_minc["SHLQBI"] = 3
	spu_cmd_maxc["SHLQBI"] = 3

	# Command: SHLQBII
	spu_cmd_list[spu_cmd_count++] = "SHLQBII"
	spu_cmd_latency["SHLQBII"] = 4
	spu_cmd_pipe["SHLQBII"] = "odd"
	spu_cmd_argv["SHLQBII", 0] = "wo"
	spu_cmd_argv["SHLQBII", 1] = "ro"
	spu_cmd_argv["SHLQBII", 2] = "im"
	spu_cmd_argc["SHLQBII"] = 3
	spu_cmd_minc["SHLQBII"] = 3
	spu_cmd_maxc["SHLQBII"] = 3

	# Command: ROTQBY
	spu_cmd_list[spu_cmd_count++] = "ROTQBY"
	spu_cmd_latency["ROTQBY"] = 4
	spu_cmd_pipe["ROTQBY"] = "odd"
	spu_cmd_argv["ROTQBY", 0] = "wo"
	spu_cmd_argv["ROTQBY", 1] = "ro"
	spu_cmd_argv["ROTQBY", 2] = "ro"
	spu_cmd_argc["ROTQBY"] = 3
	spu_cmd_minc["ROTQBY"] = 3
	spu_cmd_maxc["ROTQBY"] = 3

	# Command: ROTQBYI
	spu_cmd_list[spu_cmd_count++] = "ROTQBYI"
	spu_cmd_latency["ROTQBYI"] = 4
	spu_cmd_pipe["ROTQBYI"] = "odd"
	spu_cmd_argv["ROTQBYI", 0] = "wo"
	spu_cmd_argv["ROTQBYI", 1] = "ro"
	spu_cmd_argv["ROTQBYI", 2] = "im"
	spu_cmd_argc["ROTQBYI"] = 3
	spu_cmd_minc["ROTQBYI"] = 3
	spu_cmd_maxc["ROTQBYI"] = 3

	# Command: ROTQBYBI
	spu_cmd_list[spu_cmd_count++] = "ROTQBYBI"
	spu_cmd_latency["ROTQBYBI"] = 4
	spu_cmd_pipe["ROTQBYBI"] = "odd"
	spu_cmd_argv["ROTQBYBI", 0] = "wo"
	spu_cmd_argv["ROTQBYBI", 1] = "ro"
	spu_cmd_argv["ROTQBYBI", 2] = "ro"
	spu_cmd_argc["ROTQBYBI"] = 3
	spu_cmd_minc["ROTQBYBI"] = 3
	spu_cmd_maxc["ROTQBYBI"] = 3

	# Command: ROTQBI
	spu_cmd_list[spu_cmd_count++] = "ROTQBI"
	spu_cmd_latency["ROTQBI"] = 4
	spu_cmd_pipe["ROTQBI"] = "odd"
	spu_cmd_argv["ROTQBI", 0] = "wo"
	spu_cmd_argv["ROTQBI", 1] = "ro"
	spu_cmd_argv["ROTQBI", 2] = "ro"
	spu_cmd_argc["ROTQBI"] = 3
	spu_cmd_minc["ROTQBI"] = 3
	spu_cmd_maxc["ROTQBI"] = 3

	# Command: ROTQBII
	spu_cmd_list[spu_cmd_count++] = "ROTQBII"
	spu_cmd_latency["ROTQBII"] = 4
	spu_cmd_pipe["ROTQBII"] = "odd"
	spu_cmd_argv["ROTQBII", 0] = "wo"
	spu_cmd_argv["ROTQBII", 1] = "ro"
	spu_cmd_argv["ROTQBII", 2] = "im"
	spu_cmd_argc["ROTQBII"] = 3
	spu_cmd_minc["ROTQBII"] = 3
	spu_cmd_maxc["ROTQBII"] = 3

	# Command: ROTQMBY
	spu_cmd_list[spu_cmd_count++] = "ROTQMBY"
	spu_cmd_latency["ROTQMBY"] = 4
	spu_cmd_pipe["ROTQMBY"] = "odd"
	spu_cmd_argv["ROTQMBY", 0] = "wo"
	spu_cmd_argv["ROTQMBY", 1] = "ro"
	spu_cmd_argv["ROTQMBY", 2] = "ro"
	spu_cmd_argc["ROTQMBY"] = 3
	spu_cmd_minc["ROTQMBY"] = 3
	spu_cmd_maxc["ROTQMBY"] = 3

	# Command: ROTQMBYI
	spu_cmd_list[spu_cmd_count++] = "ROTQMBYI"
	spu_cmd_latency["ROTQMBYI"] = 4
	spu_cmd_pipe["ROTQMBYI"] = "odd"
	spu_cmd_argv["ROTQMBYI", 0] = "wo"
	spu_cmd_argv["ROTQMBYI", 1] = "ro"
	spu_cmd_argv["ROTQMBYI", 2] = "im"
	spu_cmd_argc["ROTQMBYI"] = 3
	spu_cmd_minc["ROTQMBYI"] = 3
	spu_cmd_maxc["ROTQMBYI"] = 3

	# Command: ROTQMBYBI
	spu_cmd_list[spu_cmd_count++] = "ROTQMBYBI"
	spu_cmd_latency["ROTQMBYBI"] = 4
	spu_cmd_pipe["ROTQMBYBI"] = "odd"
	spu_cmd_argv["ROTQMBYBI", 0] = "wo"
	spu_cmd_argv["ROTQMBYBI", 1] = "ro"
	spu_cmd_argv["ROTQMBYBI", 2] = "ro"
	spu_cmd_argc["ROTQMBYBI"] = 3
	spu_cmd_minc["ROTQMBYBI"] = 3
	spu_cmd_maxc["ROTQMBYBI"] = 3

	# Command: ROTQMBI
	spu_cmd_list[spu_cmd_count++] = "ROTQMBI"
	spu_cmd_latency["ROTQMBI"] = 4
	spu_cmd_pipe["ROTQMBI"] = "odd"
	spu_cmd_argv["ROTQMBI", 0] = "wo"
	spu_cmd_argv["ROTQMBI", 1] = "ro"
	spu_cmd_argv["ROTQMBI", 2] = "ro"
	spu_cmd_argc["ROTQMBI"] = 3
	spu_cmd_minc["ROTQMBI"] = 3
	spu_cmd_maxc["ROTQMBI"] = 3

	# Command: ROTQMBII
	spu_cmd_list[spu_cmd_count++] = "ROTQMBII"
	spu_cmd_latency["ROTQMBII"] = 4
	spu_cmd_pipe["ROTQMBII"] = "odd"
	spu_cmd_argv["ROTQMBII", 0] = "wo"
	spu_cmd_argv["ROTQMBII", 1] = "ro"
	spu_cmd_argv["ROTQMBII", 2] = "im"
	spu_cmd_argc["ROTQMBII"] = 3
	spu_cmd_minc["ROTQMBII"] = 3
	spu_cmd_maxc["ROTQMBII"] = 3

	# Command: ORX
	spu_cmd_list[spu_cmd_count++] = "ORX"
	spu_cmd_latency["ORX"] = 4
	spu_cmd_pipe["ORX"] = "odd"
	spu_cmd_argv["ORX", 0] = "wo"
	spu_cmd_argv["ORX", 1] = "ro"
	spu_cmd_argc["ORX"] = 2
	spu_cmd_minc["ORX"] = 2
	spu_cmd_maxc["ORX"] = 2

	# Command: SHUFB
	spu_cmd_list[spu_cmd_count++] = "SHUFB"
	spu_cmd_latency["SHUFB"] = 4
	spu_cmd_pipe["SHUFB"] = "odd"
	spu_cmd_argv["SHUFB", 0] = "wo"
	spu_cmd_argv["SHUFB", 1] = "ro"
	spu_cmd_argv["SHUFB", 2] = "ro"
	spu_cmd_argv["SHUFB", 3] = "ro"
	spu_cmd_argc["SHUFB"] = 4
	spu_cmd_minc["SHUFB"] = 4
	spu_cmd_maxc["SHUFB"] = 4

	# Command: CBD
	spu_cmd_list[spu_cmd_count++] = "CBD"
	spu_cmd_latency["CBD"] = 4
	spu_cmd_pipe["CBD"] = "odd"
	spu_cmd_argv["CBD", 0] = "wo"
	spu_cmd_argv["CBD", 1] = "ir"
	spu_cmd_argc["CBD"] = 2
	spu_cmd_minc["CBD"] = 2
	spu_cmd_maxc["CBD"] = 2

	# Command: CBX
	spu_cmd_list[spu_cmd_count++] = "CBX"
	spu_cmd_latency["CBX"] = 4
	spu_cmd_pipe["CBX"] = "odd"
	spu_cmd_argv["CBX", 0] = "wo"
	spu_cmd_argv["CBX", 1] = "ro"
	spu_cmd_argv["CBX", 2] = "ro"
	spu_cmd_argc["CBX"] = 3
	spu_cmd_minc["CBX"] = 3
	spu_cmd_maxc["CBX"] = 3

	# Command: CHD
	spu_cmd_list[spu_cmd_count++] = "CHD"
	spu_cmd_latency["CHD"] = 4
	spu_cmd_pipe["CHD"] = "odd"
	spu_cmd_argv["CHD", 0] = "wo"
	spu_cmd_argv["CHD", 1] = "ir"
	spu_cmd_argc["CHD"] = 2
	spu_cmd_minc["CHD"] = 2
	spu_cmd_maxc["CHD"] = 2

	# Command: CHX
	spu_cmd_list[spu_cmd_count++] = "CHX"
	spu_cmd_latency["CHX"] = 4
	spu_cmd_pipe["CHX"] = "odd"
	spu_cmd_argv["CHX", 0] = "wo"
	spu_cmd_argv["CHX", 1] = "ro"
	spu_cmd_argv["CHX", 2] = "ro"
	spu_cmd_argc["CHX"] = 3
	spu_cmd_minc["CHX"] = 3
	spu_cmd_maxc["CHX"] = 3

	# Command: CWD
	spu_cmd_list[spu_cmd_count++] = "CWD"
	spu_cmd_latency["CWD"] = 4
	spu_cmd_pipe["CWD"] = "odd"
	spu_cmd_argv["CWD", 0] = "wo"
	spu_cmd_argv["CWD", 1] = "ir"
	spu_cmd_argc["CWD"] = 2
	spu_cmd_minc["CWD"] = 2
	spu_cmd_maxc["CWD"] = 2

	# Command: CWX
	spu_cmd_list[spu_cmd_count++] = "CWX"
	spu_cmd_latency["CWX"] = 4
	spu_cmd_pipe["CWX"] = "odd"
	spu_cmd_argv["CWX", 0] = "wo"
	spu_cmd_argv["CWX", 1] = "ro"
	spu_cmd_argv["CWX", 2] = "ro"
	spu_cmd_argc["CWX"] = 3
	spu_cmd_minc["CWX"] = 3
	spu_cmd_maxc["CWX"] = 3

	# Command: CDD
	spu_cmd_list[spu_cmd_count++] = "CDD"
	spu_cmd_latency["CDD"] = 4
	spu_cmd_pipe["CDD"] = "odd"
	spu_cmd_argv["CDD", 0] = "wo"
	spu_cmd_argv["CDD", 1] = "ir"
	spu_cmd_argc["CDD"] = 2
	spu_cmd_minc["CDD"] = 2
	spu_cmd_maxc["CDD"] = 2

	# Command: CDX
	spu_cmd_list[spu_cmd_count++] = "CDX"
	spu_cmd_latency["CDX"] = 4
	spu_cmd_pipe["CDX"] = "odd"
	spu_cmd_argv["CDX", 0] = "wo"
	spu_cmd_argv["CDX", 1] = "ro"
	spu_cmd_argv["CDX", 2] = "ro"
	spu_cmd_argc["CDX"] = 3
	spu_cmd_minc["CDX"] = 3
	spu_cmd_maxc["CDX"] = 3

	# Command: FSMBI
	spu_cmd_list[spu_cmd_count++] = "FSMBI"
	spu_cmd_latency["FSMBI"] = 4
	spu_cmd_pipe["FSMBI"] = "odd"
	spu_cmd_argv["FSMBI", 0] = "wo"
	spu_cmd_argv["FSMBI", 1] = "im"
	spu_cmd_argc["FSMBI"] = 2
	spu_cmd_minc["FSMBI"] = 2
	spu_cmd_maxc["FSMBI"] = 2

	# Command: FSMB
	spu_cmd_list[spu_cmd_count++] = "FSMB"
	spu_cmd_latency["FSMB"] = 4
	spu_cmd_pipe["FSMB"] = "odd"
	spu_cmd_argv["FSMB", 0] = "wo"
	spu_cmd_argv["FSMB", 1] = "ro"
	spu_cmd_argc["FSMB"] = 2
	spu_cmd_minc["FSMB"] = 2
	spu_cmd_maxc["FSMB"] = 2

	# Command: FSMH
	spu_cmd_list[spu_cmd_count++] = "FSMH"
	spu_cmd_latency["FSMH"] = 4
	spu_cmd_pipe["FSMH"] = "odd"
	spu_cmd_argv["FSMH", 0] = "wo"
	spu_cmd_argv["FSMH", 1] = "ro"
	spu_cmd_argc["FSMH"] = 2
	spu_cmd_minc["FSMH"] = 2
	spu_cmd_maxc["FSMH"] = 2

	# Command: FSM
	spu_cmd_list[spu_cmd_count++] = "FSM"
	spu_cmd_latency["FSM"] = 4
	spu_cmd_pipe["FSM"] = "odd"
	spu_cmd_argv["FSM", 0] = "wo"
	spu_cmd_argv["FSM", 1] = "ro"
	spu_cmd_argc["FSM"] = 2
	spu_cmd_minc["FSM"] = 2
	spu_cmd_maxc["FSM"] = 2

	# Command: GBB
	spu_cmd_list[spu_cmd_count++] = "GBB"
	spu_cmd_latency["GBB"] = 4
	spu_cmd_pipe["GBB"] = "odd"
	spu_cmd_argv["GBB", 0] = "wo"
	spu_cmd_argv["GBB", 1] = "ro"
	spu_cmd_argc["GBB"] = 2
	spu_cmd_minc["GBB"] = 2
	spu_cmd_maxc["GBB"] = 2

	# Command: GBH
	spu_cmd_list[spu_cmd_count++] = "GBH"
	spu_cmd_latency["GBH"] = 4
	spu_cmd_pipe["GBH"] = "odd"
	spu_cmd_argv["GBH", 0] = "wo"
	spu_cmd_argv["GBH", 1] = "ro"
	spu_cmd_argc["GBH"] = 2
	spu_cmd_minc["GBH"] = 2
	spu_cmd_maxc["GBH"] = 2

	# Command: GB
	spu_cmd_list[spu_cmd_count++] = "GB"
	spu_cmd_latency["GB"] = 4
	spu_cmd_pipe["GB"] = "odd"
	spu_cmd_argv["GB", 0] = "wo"
	spu_cmd_argv["GB", 1] = "ro"
	spu_cmd_argc["GB"] = 2
	spu_cmd_minc["GB"] = 2
	spu_cmd_maxc["GB"] = 2

	# Command: FREST
	spu_cmd_list[spu_cmd_count++] = "FREST"
	spu_cmd_latency["FREST"] = 4
	spu_cmd_pipe["FREST"] = "odd"
	spu_cmd_argv["FREST", 0] = "wo"
	spu_cmd_argv["FREST", 1] = "ro"
	spu_cmd_argc["FREST"] = 2
	spu_cmd_minc["FREST"] = 2
	spu_cmd_maxc["FREST"] = 2

	# Command: FRSQEST
	spu_cmd_list[spu_cmd_count++] = "FRSQEST"
	spu_cmd_latency["FRSQEST"] = 4
	spu_cmd_pipe["FRSQEST"] = "odd"
	spu_cmd_argv["FRSQEST", 0] = "wo"
	spu_cmd_argv["FRSQEST", 1] = "ro"
	spu_cmd_argc["FRSQEST"] = 2
	spu_cmd_minc["FRSQEST"] = 2
	spu_cmd_maxc["FRSQEST"] = 2

	# Command: FSCRRD
	spu_cmd_list[spu_cmd_count++] = "FSCRRD"
	spu_cmd_latency["FSCRRD"] = 13
	spu_cmd_pipe["FSCRRD"] = "odd"
	spu_cmd_argv["FSCRRD", 0] = "wo"
	spu_cmd_argc["FSCRRD"] = 1
	spu_cmd_minc["FSCRRD"] = 1
	spu_cmd_maxc["FSCRRD"] = 1

	# Command: FSCRWR
	spu_cmd_list[spu_cmd_count++] = "FSCRWR"
	spu_cmd_latency["FSCRWR"] = 7
	spu_cmd_pipe["FSCRWR"] = "odd"
	spu_cmd_argv["FSCRWR", 0] = "ro"
	spu_cmd_argc["FSCRWR"] = 1
	spu_cmd_minc["FSCRWR"] = 1
	spu_cmd_maxc["FSCRWR"] = 1

	# Command: MFSPR
	spu_cmd_list[spu_cmd_count++] = "MFSPR"
	spu_cmd_latency["MFSPR"] = 6
	spu_cmd_pipe["MFSPR"] = "odd"
	spu_cmd_argv["MFSPR", 0] = "wo"
	spu_cmd_argv["MFSPR", 1] = "sr"
	spu_cmd_argc["MFSPR"] = 2
	spu_cmd_minc["MFSPR"] = 2
	spu_cmd_maxc["MFSPR"] = 2

	# Command: MTSPR
	spu_cmd_list[spu_cmd_count++] = "MTSPR"
	spu_cmd_latency["MTSPR"] = 6
	spu_cmd_pipe["MTSPR"] = "odd"
	spu_cmd_argv["MTSPR", 0] = "sr"
	spu_cmd_argv["MTSPR", 1] = "ro"
	spu_cmd_argc["MTSPR"] = 2
	spu_cmd_minc["MTSPR"] = 2
	spu_cmd_maxc["MTSPR"] = 2

	# Command: IRETD
	spu_cmd_list[spu_cmd_count++] = "IRETD"
	spu_cmd_latency["IRETD"] = 1
	spu_cmd_pipe["IRETD"] = "odd"
	spu_cmd_argc["IRETD"] = 0
	spu_cmd_minc["IRETD"] = 0
	spu_cmd_maxc["IRETD"] = 0

	# Command: IRETE
	spu_cmd_list[spu_cmd_count++] = "IRETE"
	spu_cmd_latency["IRETE"] = 1
	spu_cmd_pipe["IRETE"] = "odd"
	spu_cmd_argc["IRETE"] = 0
	spu_cmd_minc["IRETE"] = 0
	spu_cmd_maxc["IRETE"] = 0

	# Command: IRET
	spu_cmd_list[spu_cmd_count++] = "IRET"
	spu_cmd_latency["IRET"] = 1
	spu_cmd_pipe["IRET"] = "odd"
	spu_cmd_argc["IRET"] = 0
	spu_cmd_minc["IRET"] = 0
	spu_cmd_maxc["IRET"] = 0

	# Command: RCHCNT
	spu_cmd_list[spu_cmd_count++] = "RCHCNT"
	spu_cmd_latency["RCHCNT"] = 6
	spu_cmd_pipe["RCHCNT"] = "odd"
	spu_cmd_argv["RCHCNT", 0] = "wo"
	spu_cmd_argv["RCHCNT", 1] = "ch"
	spu_cmd_argc["RCHCNT"] = 2
	spu_cmd_minc["RCHCNT"] = 2
	spu_cmd_maxc["RCHCNT"] = 2

	# Command: RDCH
	spu_cmd_list[spu_cmd_count++] = "RDCH"
	spu_cmd_latency["RDCH"] = 6
	spu_cmd_pipe["RDCH"] = "odd"
	spu_cmd_argv["RDCH", 0] = "wo"
	spu_cmd_argv["RDCH", 1] = "ch"
	spu_cmd_argc["RDCH"] = 2
	spu_cmd_minc["RDCH"] = 2
	spu_cmd_maxc["RDCH"] = 2

	# Command: WRCH
	spu_cmd_list[spu_cmd_count++] = "WRCH"
	spu_cmd_latency["WRCH"] = 1
	spu_cmd_pipe["WRCH"] = "odd"
	spu_cmd_argv["WRCH", 0] = "ch"
	spu_cmd_argv["WRCH", 1] = "ro"
	spu_cmd_argc["WRCH"] = 2
	spu_cmd_minc["WRCH"] = 2
	spu_cmd_maxc["WRCH"] = 2

	# Command: STOP
	spu_cmd_list[spu_cmd_count++] = "STOP"
	spu_cmd_latency["STOP"] = 1
	spu_cmd_pipe["STOP"] = "odd"
	spu_cmd_argv["STOP", 0] = "!rw"
	spu_cmd_argc["STOP"] = 0
	spu_cmd_minc["STOP"] = 0
	spu_cmd_maxc["STOP"] = 1

	# Command: STOPD
	spu_cmd_list[spu_cmd_count++] = "STOPD"
	spu_cmd_latency["STOPD"] = 1
	spu_cmd_pipe["STOPD"] = "odd"
	spu_cmd_argv["STOPD", 0] = "ro"
	spu_cmd_argv["STOPD", 1] = "ro"
	spu_cmd_argv["STOPD", 2] = "ro"
	spu_cmd_argc["STOPD"] = 3
	spu_cmd_minc["STOPD"] = 3
	spu_cmd_maxc["STOPD"] = 3

}

